### ISSUE TITLE
Toyota Console Waypoint Position Possible Bug

### ISSUE THREAD

**Issue by 50ap5ud5** [Spectre0987/TardisMod#100]
**Mod Version**: 0.0.8A Hotfix 2

**Possible Bug**:
1. The Waypoint Input (Previously Waypoint Setter) button is placed in a specific, hard to access position in the Toyota Console. 
See attached image link: https://imgur.com/qKcPouz

**Comment by Spectre0987** [comment]
Yeah, that's bad. Don't worry though, I've redone the Waypoint system and it should be fixed next patch.
