### ISSUE TITLE
0.0.8A Hotfix 2 Possible Tardis Component Bugs

### ISSUE THREAD

**Issue by 50ap5ud5** [Spectre0987/TardisMod#101]
**Mod Version:** 0.0.8A Hotfix 2
**Location:** Singleplayer
**Possible Bugs:**
- Tardis Toolkit has no crafting recipe.
- Temporal Grace Circuits and Chameleon Circuits cannot be repaired by Microwelding station, only by Tardis Toolkit (which is unable to be obtained in Survival mode by crafting)
- Microwelding Station GUI prevents player from viewing any item's name and properties. Additionally, background is not darkened as seen with most vanilla GUIs. (Unsure if this is an intentional design choice). See attached image link: https://imgur.com/j1qEz0f

**Comment by Spectre0987** [comment]
The TARDIS Toolkit will be a found item if Mel ever makes any structures. Chameleon Circuit is already repairable, and I'll make the Temporal Grace Circuits just use a shield for now.

**Comment by Spectre0987** [comment]
Fixed.
