### ISSUE TITLE
BOTI glitching when far away

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [Spectre0987/TardisMod#102]
When going far out the graphics are glitching. Tested at _29955026 71 -62_ with version **Alpha 0.0.8 - Patch 2**
<details>
  <summary>Click to show screenshots</summary>

**Holoprojector:**

![2018-11-26_13 44 55](https://user-images.githubusercontent.com/27149563/49014978-124ed980-f182-11e8-888a-50c741d5698f.png)
**Tardis Door:**

![2018-11-26_13 45 00](https://user-images.githubusercontent.com/27149563/49014980-1549ca00-f182-11e8-913a-0378cd6d477e.png)
**Both:**

![2018-11-26_13 50 24](https://user-images.githubusercontent.com/27149563/49015051-42967800-f182-11e8-86d1-433636a6a63b.png)
</details>

**Comment by Spectre0987** [comment]
Yeah, that's what happens when you go that far, mod or no.
