### ISSUE TITLE
TARDIS gone, can't find it.

### ISSUE THREAD

**Issue by KeinFoster** [Spectre0987/TardisMod#119]
I tried attacking TARDIS  from outaide now it's gone, i didn't get a screwdriver, how do i find TARDIS now?

**Comment by LotuxPunk** [comment]
https://tardis-mod.com/books/commands/page/a-few-small-commands-to-make-your-life-easier#bkmrk-%2Ftardis-summon

**Comment by LotuxPunk** [comment]
And disable the HADS
