### ISSUE TITLE
Server crash : Something wrong with the ControlDoors

### ISSUE THREAD

**Issue by LotuxPunk** [Spectre0987/TardisMod#120]
https://github.com/Spectre0987/TardisMod/blob/3a66bc0029146a5dec82c130b26110bb472eba40/src/main/java/net/tardis/mod/common/entities/controls/ControlDoor.java#L141

https://pastebin.com/P0SEBFC0

**Comment by Spectre0987** [comment]
That's someone doing something weird with CC.

**Comment by Spectre0987** [comment]
That one's someone messing with CC too.
