### ISSUE TITLE
Overthinking the balacing in the mod

### ISSUE THREAD

**Issue by BurningPixels** [Spectre0987/TardisMod#123]
Maybe you should think about rebalancing the mod a bit. At the moment the Tardis is a kinda end game vehicle. It would be a good a idea to make it a little bit easier to make a tardis fully usable. I think it should be possible to just make the Tardis a "i started the game and did a few things and now i can use this" item. Or maybe add the circuits to the chest of villagers.

**Comment by Spectre0987** [comment]
Almost nothing will be craftable in the future, I just can't get my builder to make the structures I want you to find stuff in.

**Comment by BurningPixels** [comment]
Uff nice builder xD But that's a nice way to do it - just find it in structures. The structures itself shouldn't be so hard to make. Maybe a old broken tardis, so u can find the interior of an tardis somewhere. Than u need some kind of "distress receiver" so u can find there tardises.

**Comment by Spectre0987** [comment]
Actually, that's almost exactly what I had in mind, for the components at least.

**Comment by SamSational-Madden** [comment]
Oh, good.

**Comment by Spectre0987** [comment]
This is somewhat done as the TARDIS will now generate with random circuits.
