### ISSUE TITLE
Client freezing when you use a Marker item at far position

### ISSUE THREAD

**Issue by LotuxPunk** [Spectre0987/TardisMod#127]
I was on -81000 64 50000 and my client freezing when I right clicked on the ground with the marker

**Comment by 50ap5ud5** [comment]
On singleplayer it doesn't seem to freeze for me, it just records the coordinates of the block the player is looking at. Did this occur in multiplayer?

**Comment by LotuxPunk** [comment]
After reloading the game all is fine.

**Comment by Spectre0987** [comment]
It's a dev item anyway.
