### ISSUE TITLE
0.0.8A Patch 3 Initial Bugs and Enchancements

### ISSUE THREAD

**Issue by 50ap5ud5** [Spectre0987/TardisMod#130]
Location: Singleplayer 
MC Version: 1.12.2
Mod version: 0.0.8A Patch 3
Other mods installed: Mineshot, BetterFPS, World Edit, JEI

Inital Bugs List:
- Breaking Tardis monitor in survival mode drops 2 monitors instead of 1.
- Toyota Whirlgig block does not render when placed.[Invalid, issue with BetterFPS]
- Cinnabar Ore cannot be mined from Cinnabar ore with regular pickaxe
- [Possible Bug] Cinnabar Ore obtained via Silk Touch enchanted pickaxe does not smelt in furnace
- When removing Dimensional Dams from Sub-System, the Tardis kicks the player from the interior without giving back the Time Vector Generator

Enhancement:
-Waypoint Selector nametag has long name, "entity.waypointselector.name"
-When Dimensional Dams are removed, the player is not given the damaged Time Vector Generator. It remains in the interior, which forces players to craft a new TVG to access the TARDIS.

**Comment by Spectre0987** [comment]
Fixed this too, I should read these more often.
