### ISSUE TITLE
BOTI update broken w/modpack

### ISSUE THREAD

**Issue by TheStarkillerGitHub** [Spectre0987/TardisMod#137]
The BOTI update is a bit broken with the mod pack. When I used this mod before using some of the mod pack (didn't use it at all back then, only use some of it now), the BOTI update worked perfectly. Now, though, it doesn't show the outside from the inside or the inside from the outside. This sounds similar to the BOTI glitching far away glitch, but it's not. It happens close by, too. Mods being used from the New TARDIS Modpack: TARDIS Mod, 0.0.8A; Regeneration, 1.12.2-1.2.6; Weeping Angels, 31.5; Optifine, 1.12.2 HD U E1 and Just Enough Items, 1.12.2-4.13.1.225.

**Comment by honeyluck** [comment]
Is it just black?
