### ISSUE TITLE
Click on communicator during a flight is opped

### ISSUE THREAD

**Issue by LotuxPunk** [Spectre0987/TardisMod#138]
You can travel faster on event by clicking on ringing communicator before the end of a travel

**Comment by Suffril** [comment]
Steps to reproduce? I don't seem to get this issue
Could you make a streamable?

**Comment by MishaPlayer** [comment]
I've witnessed and done this before by accident, OP is basically saying that you could make a short flight, quickly change the coordinates before the TARDIS lands, and land at a far away distance or an invaded village at the same amount of time and artron energy the short flight would've costed.

**Comment by Spectre0987** [comment]
Fixed. (It's 'cause I'm amazing)
