### ISSUE TITLE
Tardis Interior Door Rotation Bugs

### ISSUE THREAD

**Issue by 50ap5ud5** [Spectre0987/TardisMod#144]
**Mod Version:** 0.0.8A Patch 3
**Location:** Singleplayer
**List of other installed mods:**
- BetterFps
- Mineshot
- World Edit Forge
- JEI

**Description:**
The Tardis interior doors can be placed inbetween two blocks by Sneak + Right clicking for aesthetics purposes.
However when the door is placed this way in different directions, the block has some rotation/visual issues.

- **Player Facing North:** Door becomes embedded inside the wall blocks.
![north](https://user-images.githubusercontent.com/22887654/50618524-80d44380-0f47-11e9-9723-3f57d9375686.png)
- **Player Facing West:** Door shifts to the right of wall blocks
![west](https://user-images.githubusercontent.com/22887654/50618556-bed16780-0f47-11e9-98cc-aeff4a312332.png)
**Player Facing South:** Door comes forward slightly, but does not touch wall blocks.
![south](https://user-images.githubusercontent.com/22887654/50618559-cc86ed00-0f47-11e9-8a98-f488d24001cb.png)
- **Player Facing East:** Door is shifted to the left of wall blocks.
![east](https://user-images.githubusercontent.com/22887654/50618566-dad50900-0f47-11e9-9df3-9669617afd24.png)

**Comment by honeyluck** [comment]
I will look into this issue tomorrow / later when I get the time

**Comment by Suffril** [comment]
Is this still a problem?

**Comment by 50ap5ud5** [comment]
I believe they are partially fixed. In 0.0.9B the door at west and east are ok, but it's still an issue when the doors are facing north and south. See the attached image. I reproduced this using the same method as my original post, using Sneak + Right click to place the doors, which centres it between two blocks.

![door bug 0 0 9b labelled](https://user-images.githubusercontent.com/22887654/54559856-1c3c6700-4a15-11e9-9ea6-b652cedf2134.png)
