### ISSUE TITLE
Hum possibly played twice

### ISSUE THREAD

**Issue by LotuxPunk** [Spectre0987/TardisMod#148]
https://github.com/Spectre0987/TardisMod/blob/8b5126964abb0a625b2e198ceb1fda2d5e7d32b3/src/main/java/net/tardis/mod/common/tileentity/TileEntityTardis.java#L232

https://github.com/Spectre0987/TardisMod/blob/8b5126964abb0a625b2e198ceb1fda2d5e7d32b3/src/main/java/net/tardis/mod/common/tileentity/TileEntityTardis.java#L236

Isn't the hum play twice ?

**Comment by Suffril** [comment]
Yes, We want the first one 
It's probably due to a git merge gone badly
