### ISSUE TITLE
Unable to join personal server after travelling to new dimension in tardis

### ISSUE THREAD

**Issue by giguga** [Spectre0987/TardisMod#151]
I tried joining my server after the tardis took me to a dimension that when I exited the tardis looked like the overworld where my house was but none of the chunks near me loaded then I crashed and on trying to rejoin it gives an error. 
[latest.log](https://github.com/Spectre0987/TardisMod/files/2743571/latest.log)

**Comment by Suffril** [comment]
This actually seems to be a problem with EnderIO and not us
