### ISSUE TITLE
Multiple Rendering

### ISSUE THREAD

**Issue by MrSalimoc** [Spectre0987/TardisMod#157]
When more than 1 TARDIS is opened, there is only 1 interior rendered.
That's not a crash or an error, i don't know if its a mistake or if you did this..

![2019-01-18_14 03 36](https://user-images.githubusercontent.com/8081840/51388571-28e23300-1b2a-11e9-9d60-3af169fa112b.png)

**Comment by Suffril** [comment]
Was this in Multiplayer or Singleplayer?

**Comment by MrSalimoc** [comment]
I was on LAN then "Singleplayer".

**Comment by Suffril** [comment]
So one exterior belongs to you and the other belongs to another player?
How did the blue exterior come into existence?

**Comment by Spectre0987** [comment]
Yeah, this is tied to the hand not rendering @Suffril.

**Comment by Spectre0987** [comment]
Fixed in 0.0.9A
