### ISSUE TITLE
Multiple open doors at once may cause a crash (comes with log)

### ISSUE THREAD

**Issue by MishaPlayer** [Spectre0987/TardisMod#161]
[crash-2019-01-19_16.33.08-client.txt](https://github.com/Spectre0987/TardisMod/files/2780810/crash-2019-01-19_16.33.08-client.txt)
I crashed a bit later so if it's not related I'll upload the file before this one

**Comment by Suffril** [comment]
Regeneration issue, its to do with our sound handling 
Take it there

**Comment by MishaPlayer** [comment]
Oh, then that's the one from later, here you go
[crash-2019-01-19_14.45.05-client.txt](https://github.com/Spectre0987/TardisMod/files/2780820/crash-2019-01-19_14.45.05-client.txt)

**Comment by Spectre0987** [comment]
Think this is fixed too, reopen if it proves to not be after the update.
