### ISSUE TITLE
Interior door does not open

### ISSUE THREAD

**Issue by WitherTech** [Spectre0987/TardisMod#169]
I cannot leave my tardis Because the interior door does not open
The only way to leave is to remove dimensional dams subsystem

**Comment by Suffril** [comment]
Please provide a video of you encountering this issue. We can't work off the information you've given us.

**Comment by WitherTech** [comment]
When I get home I will record it
It occurred last night

**Comment by WitherTech** [comment]
I can’t seem to reproduce it, but if it happens again I will update this issue

**Comment by Spectre0987** [comment]
That just means that the TARDIS didn't land correctly to fix this, take off and land again.
