### ISSUE TITLE
Dedicated server crash (Git build)

### ISSUE THREAD

**Issue by Reginald-Halifrax** [Spectre0987/TardisMod#177]
Here is a dedicated server crash with a build as of commit ada98871462135c3873f3affd960a253d3eb1e8e:

[Crash Log](https://pastebin.com/FDFNzipx)

[Server Log](https://pastebin.com/ZVwxX6HL)

The crash happens as soon as a tardis is grown.

only mod on the entire server was the tardis mod.

I'm aware everything is in alpha and me using a git build was sure to go wrong, but with no server tests as of yet I figured I'd do it. Hope it works out!

**Comment by Suffril** [comment]
@lotuxpunk Lotux, You forgot a @SideOnly

**Comment by LotuxPunk** [comment]
No, @SideOnly not needed, I know how topo fix it
