### ISSUE TITLE
Ticking block crash

### ISSUE THREAD

**Issue by Reginald-Halifrax** [Spectre0987/TardisMod#179]
With a build using commit 66823a4648cda8c969e4967e66a2b2468b982028, using a projectE watch of flowing time to increase Tardis coral ticks, you can crash the game.

[Crash Log](https://pastebin.com/BjUQZxpW)

[Game Output Log](https://pastebin.com/eVdTCcR8)

If I'm not correct this crash didn't exist until now, possibly occurred after the coral itself was changed to have growth states.

Even though I don't believe players should be allowed to uptick Tardis functionality anywhere, it should always be expected. Hope I helped!

**Comment by Spectre0987** [comment]
We don't accept issues from releases we are working on. If it was ready, It'd be released. That being said, the was exceedingly helpful as this would have made the new release unplayable. Thank you!

**Comment by Reginald-Halifrax** [comment]
Just doin' my job reporting issues, if there was a development issue I could post I would!

**Comment by Spectre0987** [comment]
lol thanks, we had to add that rule when people kept building their own and DMing me about things not working while I as creating them.

**Comment by Reginald-Halifrax** [comment]
I'll be sure to only say things if it seems like something unnoticed or obscure if its truly gamebreaking from now on then!
