### ISSUE TITLE
Surprise, bug report.

### ISSUE THREAD

**Issue by MishaPlayer** [Spectre0987/TardisMod#180]
It's a compatibility issue with Handles, because the computer interface subsystem (Yes, Lotux added that) doesn't have a warning for the new subsystem removal warning interface, and it crashed.
Here's a [link](https://github.com/LotuxPunk/Handles/issues/4), close it if it belongs in Handles's github (It does, but here's an issue for you anyways because why the fuck not?)

**Comment by Spectre0987** [comment]
Yeah, that's going to be for Handles, thanks!
