### ISSUE TITLE
[0.0.9A] Initial Release bugs

### ISSUE THREAD

**Issue by 50ap5ud5** [Spectre0987/TardisMod#182]
**Mod Version:** 0.0.9A
**Other mods installed:**
- JEI
- Mineshot
- WorldEdit Forge

**Description:**

_Missing Crafting recipes_
- Thermo-coupling 
- Sonic workbench
- Item Materializer
- All Space Suit components
- Void Specs
- Bowtie
- Fez
- First Doctor's Hat
- Fourth Doctor's Hat
- First Doctor's Cane

_Missing Repair recipe:_ Thermo-Coupling

_Enhancement-related_
- Restoring all sub systems using command `/tardis restoresys` produces long chat message as shown below,
![image](https://user-images.githubusercontent.com/22887654/52518741-8e49bf80-2ca3-11e9-9ae3-7f04333a18b9.png)
- If player's inventory is full when the Tardis has grown, the player does not receive the Tardis and must craft their own.
- Dimensional dams Removal message does not have lang. file translation. Currently states "door.tardis.relocating"

Other bugs:
- Users cannot load ironic power cells into dalek ray gun.

Possible bugs (unsure)
- All new Sonic screwdrivers (4th-9th/10th, Sonic Lipstick, Lance, Romana Sonic) do not have crafting recipes. (Is it due to it being planned for acquisition via sonic workbench?)
_EDIT: This is intentional as the sonic workbench allows the user to switch sonic models at will, thus no crafting recipe for the variants are needed._ 
- Using /time set 23999 to view each Tardis Coral stage, the coral still renders when the the hell bent exterior materialises.
https://cdn.discordapp.com/attachments/449741434120044544/543786371613982730/gif.materialise.gif

**Comment by Spectre0987** [comment]
The sonic workbench is in the mod.

**Comment by Spectre0987** [comment]
You put a sonic into the slot, and select the sonic you want.

**Comment by 50ap5ud5** [comment]
Thanks for the clarification. What I meant in the issue report is that there is no way to craft the sonic workbench in survival mode.

**Comment by Spectre0987** [comment]
RIP there should have been.

**Comment by Spectre0987** [comment]
Fixed the spam when you use /tardis restorsys

**Comment by Spectre0987** [comment]
All these have now been fixed.
