### ISSUE TITLE
[0.0.9A] [Reproduced] Tardis Interior Changing Bugs

### ISSUE THREAD

**Issue by 50ap5ud5** [Spectre0987/TardisMod#183]
**Mod Version:** 0.0.9A
**Other mods installed:**

* JEI
* Mineshot
* WorldEdit Forge

**Description:**

1. Using the "Change Interior" protocol on the Tardis monitor does not delete the default interior's door entities
2. The Hell Bent door and interior door entities cannot be broken or allow the player to exit the Tardis.
3. Changing the interior back to Hell Bent interior retains the same bug as `#1`, but now any falling blocks such as anvils or sand placed in a (approximately) 3x3 area around the door entity causes the blocks to become unbreakable much like the doors.

The log consoles will spam, `[20:20:23] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 4682ms behind, skipping 93 tick(s)` and similar messages

**Reproduction steps:**

1. Create new world

1. Place and grow Tardis coral. Use /tardis grow to speed up process
2. Enter Tardis
3. Change Interior to new 0.0.9 Interior using its monitor Protocol
4. Encounter Bug `#1` 
5. Attempt to break tile entities
6. Attempt to exit Tardis using one of the doors. Encounter Bug `#2`
7. Change interior back to Hell Bent interior
8. Attempt to break tile entity doors again. Encounter Bug `#1` again.
9. Place anvils and/or sand near the bugged interior doors. All anvils and sand "inherit" the unbreakable properties of the door.

Log file:
[interior changing bugs.log](https://github.com/Spectre0987/TardisMod/files/2847681/interior.changing.bugs.log)

Video: https://www.youtube.com/watch?v=4kCFg-HlEfA&feature=youtu.be

**Comment by Spectre0987** [comment]
That's desync, it's been fixed.

**Comment by LotuxPunk** [comment]
I don't have any AT in Handles
