### ISSUE TITLE
[0.0.9A] Crash when you open a TARDIS newly created

### ISSUE THREAD

**Issue by LotuxPunk** [Spectre0987/TardisMod#185]
I am experiencing this bug while I fix the bugs on Handles

https://pastebin.com/HPcrXhdB

**Comment by Suffril** [comment]
Looks like you didnt set up your workspace correctly

**Comment by LotuxPunk** [comment]
I disable the BOTI, and all is fine now.

What do you mean ? Tbh, I just change the version of TARDIS Mod and run a setupDecompWorkspace :D

**Comment by Spectre0987** [comment]
That's your ATs

**Comment by Suffril** [comment]
@Spectre0987 Actually, this seems to be happening to a few users aswell

**Comment by Spectre0987** [comment]
You need to update the build.gradle

**Comment by Spectre0987** [comment]
Really?

**Comment by Suffril** [comment]
Yeah, some dude mentioned it earlier

**Comment by LotuxPunk** [comment]
I don't have any AT in Handles

**Comment by Suffril** [comment]
He means your deps ATs, but I'll look into this

**Comment by LotuxPunk** [comment]
I don't get it... 😖

**Comment by Spectre0987** [comment]
This is fixed with Fril's reflection.
