### ISSUE TITLE
[0.0.9A] Sonic Screwdriver Bugs/Enhancement

### ISSUE THREAD

**Issue by 50ap5ud5** [Spectre0987/TardisMod#195]
**Mod Version:** 0.0.9A
**Other mods installed:**
- JEI
- Mineshot
- WorldEdit Forge
- Dalek Mod

**Bugs:**
- Sonic Screwdriver uses 5 charge when switching to Block Interactions mode and Signal Tardis Mode, however this does not occur when switching to other modes.

/* It seems that the changing mode controls (Sneak+Right click on ground) is the issue - when the sonic switches to Block Interactions it detects the block being interacted with is not in its range of capabilities, but still uses charge regardless. */

**Enhancement:**
- Sonic Screwdriver still uses 5 charge when the player interacts with the top part of an iron door. While this encourages users to understand their tools better, this can be a slight irritation if the player accidentally clicks the top part of an iron door and loses 1/20 of their total charge.

Video: https://www.youtube.com/watch?v=TmKiWN7u3wc

**Comment by Josia50** [comment]
This function is still in the mod though (Signal Tardis).?

**Comment by 50ap5ud5** [comment]
Ok. I'm not sure if it was disabled or if I was not using it properly. I will amend that part.

**Comment by ydna111** [comment]
Yea it is still in. I've tried it.
