### ISSUE TITLE
[0.0.9A] Sonic Workbench Bugs/Enhancement

### ISSUE THREAD

**Issue by 50ap5ud5** [Spectre0987/TardisMod#196]
**Mod Version:** 0.0.9A
**Other mods installed:**
- JEI
- Mineshot
- WorldEdit Forge
- Dalek Mod

**Bugs:**
- Workbench has no crafting recipe (unobtainable in survival mode) [Previously mentioned in #182 ]
- When the GUI is open, all items in the inventory and GUI will not display their tooltip. See the below screenshots for reference.

_Before:_
![2019-02-11_02 44 50](https://user-images.githubusercontent.com/22887654/52536181-34342180-2dab-11e9-8e19-3b7159d2b1fc.png)

_After:_
![2019-02-11_02 44 55](https://user-images.githubusercontent.com/22887654/52536182-3a2a0280-2dab-11e9-9f23-e627d0718aad.png)

**Enhancement**
- Not so much a bug, more of an enhancement question. If the workbench is broken with a sonic still stored in its slot, it will not drop the sonic. 
   - This can be frustrating for users who may have forgotten to remove their sonic screwdriver from the workbench. 
   - On the other hand, this encourages players to be more careful of how they use their tools and provides a sense of realism. (E.g. Destroying a table with a tool such as a computer still placed on it may result in the computer being damaged/destroyed along with the table)

**Comment by Suffril** [comment]
Whoever made the crafting recipe made a typo in the word keys 


![2019-02-10_18 00 34](https://user-images.githubusercontent.com/36424503/52537365-f361eb80-2d5d-11e9-91ac-457333c623ee.png)
