### ISSUE TITLE
[0.0.9A] [Reproduced] [Known] Entities are easily teleported back into Tardis interior

### ISSUE THREAD

**Issue by 50ap5ud5** [Spectre0987/TardisMod#197]
**Mod Version:** 0.0.9A

**Other mods installed:**
- JEI
- Mineshot
- WorldEdit Forge
- Dalek Mod

**Description:**
- Tardis teleportation range is too small. When an entity leaves the Tardis interior via the doors, the entity is teleported back into the interior due to small teleportation range.
  - The player cannot interact with the entity during this bug.
  - If the player enters then attempts to exit the Tardis during the bug, they will be pushed inside by the entity. The only way to exit is to sprint and push the entity to the side as the player steps out of the interior.
  - This can only be fixed by closing the Tardis doors, (shutting the entity inside) then opening the doors. After this will the companion be able to freely move around the exterior.

**Reproduction:**
1. Place and grow a Tardis coral.
2. Rescue/summon a companion. This method is easiest to view the issue.
3. Ask companion to wait at the player's position. Ensure the player is not near the Tardis exterior
3. Open Tardis doors with key
4. Ask companion to return to Tardis
5. Bug occurs - companion will constantly teleport in and out of the Tardis.

_Video demonstration:_ https://www.youtube.com/watch?v=2_lEl_e1Vpw

Log file: 
[tardis entity teleport bug 0.0.9.log](https://github.com/Spectre0987/TardisMod/files/2849112/tardis.entity.teleport.bug.0.0.9.log)

(Relevant logs start at `[02:47:13] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 2542ms behind, skipping 50 tick(s)`:

**Comment by 50ap5ud5** [comment]
It appears this issue is known and a solution has already been made. It's success is yet o be determined. 

See:  https://github.com/Spectre0987/TardisMod/commit/58a6599efd39f75bcc4f3fb057e91d86538ed247

**Comment by Josia50** [comment]
Yeah, They were being teleported out too short, causing them to come back in.

**Comment by 50ap5ud5** [comment]
Fixed in https://github.com/Spectre0987/TardisMod/commit/58a6599efd39f75bcc4f3fb057e91d86538ed247

**Comment by Spectre0987** [comment]
People bitch about it putting you to far and now not putting you far enough. I don't care.
