### ISSUE TITLE
Thermo-coupling removal while landed still results in TARDIS self-materialization.

### ISSUE THREAD

**Issue by MishaPlayer** [Spectre0987/TardisMod#205]
Steps:

1. Obtain a TARDIS.
2. Make sure it has thermo-couplings in the first place.
3. Remove them.

You'll see that regardless of flight system, fluid links and other stuff, it'll land inside of itself, guaranteed.

**Comment by Suffril** [comment]
Legit just sounds like intended behavior.

**Comment by MishaPlayer** [comment]
I'm not sure if this is intended, as it would make it a bit difficult to repair said subsystem if someone wasn't aware of this.

**Comment by Spectre0987** [comment]
That's a feature, seen in the mini- episode Time and Space (Two different episodes)

**Comment by MishaPlayer** [comment]
I know, but it happens while landed.

The reproduction steps say nothing about taking off or removing them _mid-flight_, though.
In said episode, it was shown that Rory dropped them while The Doctor and Rory were performing maintenance on the TARDIS while it was in the vortex. (or conceptual space)

**Comment by MishaPlayer** [comment]
I'd rather this be re-opened, as said earlier that it makes sense that it would land inside of itself if they failed mid-flight or were at 0% durability when the player tries to activate flight, but not while it's landed and should not be taking off.
