### ISSUE TITLE
Thermo-Coupling bug re-explained (With video)

### ISSUE THREAD

**Issue by MishaPlayer** [Spectre0987/TardisMod#206]
Okay, so you didn't understand the last issue I made and closed it. Maybe I was a bit too vague.

1. TARDIS is _landed_, meaning damage to this subsystem would result in it presumably being unable to take off.
2. Remove the TC, and find that- Oh shit, it's Red Nose Day
3. Replace the subsystem to get out.

[You can see a visual representation of this](https://youtu.be/BkU_GPM7UcQ)

**Comment by Spectre0987** [comment]
Damage is done only when the TARDIS initializes a landing. This would make it never land inside of itself.

**Comment by MishaPlayer** [comment]
I'm trying to say that the TARDIS will land inside of itself regardless of anything stopping it:

- No subsystems that would allow for flight
- Being landed (It probably landed inside of itself in the minisodes because it was in flight and had to materialize in the safest place which _happened_ to be its own interior)
- (presumably) zero Artron Energy or TARDIS Hull

**Comment by Spectre0987** [comment]
It's staying this way until the 1.13 re-write.
