### ISSUE TITLE
Can't place a corridor door in my west wall

### ISSUE THREAD

**Issue by coco777777** [Spectre0987/TardisMod#208]
The hellbent corridor door can't be place in a west or east wall, no matter what angle you look at it from.
![2019-02-22_09 05 07](https://user-images.githubusercontent.com/47884723/53231533-0ee3c500-3681-11e9-8e98-cdc1087bde16.png)
![2019-02-22_09 06 22](https://user-images.githubusercontent.com/47884723/53231567-2622b280-3681-11e9-99a3-15d53204355d.png)
![2019-02-22_09 07 02](https://user-images.githubusercontent.com/47884723/53231610-3dfa3680-3681-11e9-9320-429917c0d964.png)

UPDATE: And now I just found out that when you exit and enter the tardis again, the previously placed doors respawn.
![2019-02-22_09 12 12](https://user-images.githubusercontent.com/47884723/53232029-21aac980-3682-11e9-9198-59563813e836.png)

**Comment by Spectre0987** [comment]
Fixed in alpha 0.1.0
