### ISSUE TITLE
[0.0.9B] BOTI crash again. I'm sorry Spectre.

### ISSUE THREAD

**Issue by LotuxPunk** [Spectre0987/TardisMod#211]
https://paste.dimdev.org/ikokurirux.mccrash

**Comment by Spectre0987** [comment]
This doesn't look like an issue with BOTI. Any context?

**Comment by LotuxPunk** [comment]
Here another crash: https://paste.dimdev.org/icijisanoj.mccrash

That happen randomly when a tardis is open in the area.

**Comment by Suffril** [comment]
Spec:

![giphy](https://user-images.githubusercontent.com/36424503/53368357-6bc0d300-3940-11e9-9b2a-66954312957a.gif)

**Comment by Spectre0987** [comment]
Do you know what mods are rendering.

**Comment by LotuxPunk** [comment]
I don't get Hat do you mean...😅

**Comment by Spectre0987** [comment]
Do you know what other mod blocks are in the vicinity?

**Comment by LotuxPunk** [comment]
Tbh, that happen a lot without the same environnement.

**Comment by Spectre0987** [comment]
Noting I can do then.
