### ISSUE TITLE
Orange skies with TARDIS Mod, setting graphics to Fast makes it more orange-ish

### ISSUE THREAD

**Issue by MishaPlayer** [Spectre0987/TardisMod#212]
Idk how to reproduce, here's screenshots. Only mods that were installed is regen and tardis. 
![2019-02-23_19 53 02](https://user-images.githubusercontent.com/35854740/53293598-d0dfc180-37a4-11e9-9236-38116f4cf352.png)
![2019-02-23_19 53 14](https://user-images.githubusercontent.com/35854740/53293599-d1785800-37a4-11e9-8495-9385c25fcd76.png)
![2019-02-23_19 53 25](https://user-images.githubusercontent.com/35854740/53293600-d1785800-37a4-11e9-89cd-fb3d83335f09.png)

**Comment by CommandrMoose** [comment]
Already known and fixed, will be fine in the next patch.

**Comment by Suffril** [comment]
Read past issue reports before making a new one. This has already been reported and fixed. 
I also find it entertaining that you post about being done with the mod on Reddit and how you don't care about it....yet you report issues and play them...?

People are weird. Issue closed.
