### ISSUE TITLE
Minecraft bug or lag.

### ISSUE THREAD

**Issue by bugreporter12** [Spectre0987/TardisMod#219]
I was playing with alot of mods and i downloaded and played the tardis mod.
First i could not open the tt capsule i grew so i destroyed it and did /tardis interior.
Then i went inside. After that i put all the neccisary items like the circuits into the console and changed the console and the exterior and the interior to what i want.
Next i set a destination and i went there then i opend my tardis went outside and the lag was extreme 1 to 0 fps. But the moment i teleported away from the tardis or i went back inside it was over?.
Now later i unistalled the mod loaded the world and i did not have lag even tho i was at the same spot.
Then later i onoy loaded the world with the tardis mod. And the lag returned. Also i could not close the doors when inwas outside. Now i think there is something wrong with the gamerenderer because of the tardis i think the problem is that it renders the interior so pls put an option to turn it off so maybe it will load better and the fps is better.

**Comment by Suffril** [comment]
I'm having great difficulty understanding what the issue is due to the grammer used, would you mind editing your issue so that it's more readable?

**Comment by bugreporter12** [comment]
Oke well what i sayed was, when i grew the tardis the doors would not open.
And if i exit the tardis it gives me extreme lag no matter how many mods i have installed or how my rendering is. But if i don’t have the mod installed i don’t have lag. So the tardis is giving me lag even tho nothing has changed about it. So i think maybe its because it renders the interior so maybe you could have an option of disabling the rendering of the interior and maybe the exterior when the doors are open.

**Comment by bugreporter12** [comment]
I have fixed the problem.
Well more avoided the problem.
How?
Well create new world and use an older version of the mod. :p

**Comment by CommandrMoose** [comment]
"maybe you could have an option of disabling the rendering of the interior and maybe the exterior when the doors are open."

That's been an option since Bigger on the Inside was added

**Comment by bugreporter12** [comment]
Oke thank you and when i disabled it the lag was gone.
Not completly but most of it.
The rest of the lag is because my laptop is bad.
