### ISSUE TITLE
Crash when entering TARDIS for the first time.

### ISSUE THREAD

**Issue by ProsperCraft** [Spectre0987/TardisMod#221]
I placed a TARDIS coral in creative, then used /tardis grow to grow it then when entering I crashed to desktop.

https://gist.github.com/ProsperCraft/976f19f79365e3c3fbb8f9cfcf5c4da5

**Comment by ProsperCraft** [comment]
This also happens if a player in survival makes the TARDIS and goes in it on the server, now they can't log in without crashing over and over.

**Comment by Reveter** [comment]
Crash log after entering TARDIS

https://gist.github.com/Reveter/102a811162694301276e221a682f0f94

**Comment by Suffril** [comment]
I believe Spectre has been looking into this
Not sure if he's resolved or not 

Basically the buffer builder is trying to build when it's already building

Should be a update really soon addressing it

**Comment by Suffril** [comment]
In the meantime, disabling BOTI make fix this

**Comment by ProsperCraft** [comment]
Disable clientside or serverside or both?

**Comment by Suffril** [comment]
Client

**Comment by ProsperCraft** [comment]
The sky goes orange when looking at the TARDIS

![2019-03-12_13 23 40](https://user-images.githubusercontent.com/4427684/54229552-1bae4880-44ca-
11e9-81de-41014051e1ce.png)

**Comment by Suffril** [comment]
Also already fixed for next update haha

**Comment by ProsperCraft** [comment]
Confirmed turning this off clientside stops the crashing and massive FPS drop.
