### ISSUE TITLE
Holding a food machine in your hand renders it at your feet.

### ISSUE THREAD

**Issue by ProsperCraft** [Spectre0987/TardisMod#222]
![2019-03-12_17 33 23](https://user-images.githubusercontent.com/4427684/54243187-1282a300-44ed-11e9-9742-33b7aad17b48.png)

**Comment by Suffril** [comment]
We've asked the modeller to fix this
It's actually a issue with model transforms in the JSON

**Comment by Spectre0987** [comment]
Implemented a new model without this issue.
