### ISSUE TITLE
[FEATURE REQUEST] Barrier blocks between TARDIS areas.

### ISSUE THREAD

**Issue by ProsperCraft** [Spectre0987/TardisMod#224]
Right now the TARDIS gives a false sense of security as players can just fly from one to the other, it would be amazing if the blueprints could include a complete cube of barrier blocks around them to protect malicious players from griefing other players.  

Creative mode admins could still get through them, but then players would be protected.

**Comment by ProsperCraft** [comment]
Because it already happened--

![2019-03-17_11 09 39](https://user-images.githubusercontent.com/4427684/54495106-98646c80-48a6-11e9-9fb6-7b207fecb99e.png)
![2019-03-17_11 09 55](https://user-images.githubusercontent.com/4427684/54495110-9c908a00-48a6-11e9-8f61-2158d8d89ac5.png)
![2019-03-17_11 10 11](https://user-images.githubusercontent.com/4427684/54495115-a0241100-48a6-11e9-9e56-5a1f8e7151c5.png)
![2019-03-17_11 11 55](https://user-images.githubusercontent.com/4427684/54495118-a4502e80-48a6-11e9-856d-727a772dfa67.png)

**Comment by Suffril** [comment]
Well that must have taken a lot of dedication lmao

**Comment by Spectre0987** [comment]
Barrier blocks wont happen, but you can no longer move between TARDISes.
