### ISSUE TITLE
Client console spam about [Client thread/ERROR] [minecraft/NetHandlerPlayClient]: Received invalid update packet for null tile entity at BlockPos{x=-365, y=27, z=345} with data: {angle:270.0f}

### ISSUE THREAD

**Issue by ProsperCraft** [Spectre0987/TardisMod#225]
https://gist.github.com/ProsperCraft/37a79c33bde983eec325e6518ccd0f31

![2019-03-13_13 39 39](https://user-images.githubusercontent.com/4427684/54310140-4dd9ac00-4597-11e9-83fc-6abf5ba0c8e3.png)
This is the TARDIS in question.

**Comment by Spectre0987** [comment]
Fixed in 0.1.0C
