### ISSUE TITLE
Placing this door - unable to rotate, unable to break.

### ISSUE THREAD

**Issue by ProsperCraft** [Spectre0987/TardisMod#226]
when you place this door that is missing a name- 

![2019-03-13_13 56 48](https://user-images.githubusercontent.com/4427684/54310459-09024500-4598-11e9-8a8e-6c1ebb0d3f12.png)

It doesn't care what direction you are facing, it places the same way.

Then you are unable to target it to remove it - 

![2019-03-13_13 56 55](https://user-images.githubusercontent.com/4427684/54310497-1ae3e800-4598-11e9-80c5-63eab939d0cd.png)

**Comment by Suffril** [comment]
Fixed by captain specco
