### ISSUE TITLE
Sleeping in the TARDIS doesn't set your spawn point.

### ISSUE THREAD

**Issue by ProsperCraft** [Spectre0987/TardisMod#228]
If you sleep in a bed in your TARDIS you don't spawn there when you die, you end up at world spawn.

**Comment by Spectre0987** [comment]
If I allowed players to spawn in that dimension if a player hadn't set set their spawn they'd fall into the void forever.

**Comment by ProsperCraft** [comment]
I don't know if it possible but..
does player have a bed set in TARDIS dim? yes- spawnt here..no - send to overworld spawn.

**Comment by Spectre0987** [comment]
It's not really.
