### ISSUE TITLE
Enderdragon can fly in to your TARDIS and destroy it.

### ISSUE THREAD

**Issue by ProsperCraft** [Spectre0987/TardisMod#231]
This is what happens when you leave your door open in the end, the dragon flies in and blows up your control room.
The dragon then duplicates and there is one at 0 0 in the TARDIS dim, and one in the end.

Can we blacklist the Dragon from using the door, please?

![2019-03-17_15 28 29](https://user-images.githubusercontent.com/4427684/54498195-6ca6ae00-48c9-11e9-8c21-86b5b1f1d8bd.png)

**Comment by Spectre0987** [comment]
No entities will be black listed form the TARDIS, it's part of the fun. XD
Just make sure you shut your door.

**Comment by Spectre0987** [comment]
Actually I didn't read the part where the dragon duplicates, that'll need to be fixed.
