### ISSUE TITLE
[Feature Request] Indestructible consoles.

### ISSUE THREAD

**Issue by ProsperCraft** [Spectre0987/TardisMod#232]
If the console gets destroyed, an admin has to get involved to delete the old TARDIS so they can create a new one, or spawn one in from creative.  If they were not allowed to be destroyed then this would not be an issue.  Of if they were craftable.

**Comment by Suffril** [comment]
They are not allowed to be destroyed, how are you managing that?

**Comment by ProsperCraft** [comment]
Ender Dragon...see #231

**Comment by Suffril** [comment]
I can see how that can be a problem, I'll see what I can do later on
