### ISSUE TITLE
Crashed when i entred tardis, no possibility to reload my world.

### ISSUE THREAD

**Issue by Varlgas** [Spectre0987/TardisMod#236]
Hello, i was finishing some work yesterday night, and since i was a little lazy, i switched into creative to plant a tardis coral on the floor.. then i deleted the one in my inventory and waited for it to grow, it grow, i enter, i crash and i get the message :
"The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Already building!"
[crash-2019-03-21_23.39.34-client.txt](https://github.com/Spectre0987/TardisMod/files/2997477/crash-2019-03-21_23.39.34-client.txt)

So i tried reloading the game, and it gives me the same message.

[crash-2019-03-22_17.55.53-client.txt](https://github.com/Spectre0987/TardisMod/files/2997475/crash-2019-03-22_17.55.53-client.txt)

I sent the 2 crashlogs to maybe help a lil better ? Thanks for the answer.

**Comment by Suffril** [comment]
Already fixed next update, thanks for reporting anyways!

**Comment by Varlgas** [comment]
So i cant do anything to my world to get it back except waiting for the next update..?

**Comment by Suffril** [comment]
You can also turn off BOTI In the config :)

**Comment by Varlgas** [comment]
Thanks it was resolved !
