### ISSUE TITLE
Dedicated server crash when unlocking a TARDIS with a TARDIS key - 0.0.4a

### ISSUE THREAD

**Issue by UniversalMigrator** [Spectre0987/TardisMod#24]
Getting a dedicated server crash when trying to unlock an existing TARDIS with a TARDIS key,

crash report: https://pastebin.com/XHtp96yK

**Comment by Spectre0987** [comment]
Do you happen to have any other information?

**Comment by Spectre0987** [comment]
The crash report doesn't indicate my mod, so I assume that it's interacting with another mod weirdly.
