### ISSUE TITLE
Network Lag from Large Packets

### ISSUE THREAD

**Issue by Reveter** [Spectre0987/TardisMod#241]
Investigating some localized network lag at a group base on a server, I believe I have identified the source being the TARDIS mod sending very large packets. Since this is a communal base there are several TARDISes there at any given time. 

I have included a snippet of the packets I am referring too, along with a screenshot showing how high the network traffic is at the base, and a log of the packets while playing on the server.

`Recieved a packet from tardis. It has 1048576 bytes of data. Type is class net.tardis.mod.client.worldshell.MessageSyncWorldShell.`

![csampler packet tracker](https://user-images.githubusercontent.com/8112174/55120787-c11e0a80-50cd-11e9-8266-3770d08baabb.png)
[packet.log](
https://gist.github.com/Reveter/e2fdf392ffbe0c266d5b11cf1a0f8f21)

**Comment by Spectre0987** [comment]
I Made BOTI a request- based system, so this should no longer happen.
