### ISSUE TITLE
Boti renders in Flight and doesn't change

### ISSUE THREAD

**Issue by Josia50** [Spectre0987/TardisMod#247]
You can fly the tardis with the doors open , and see the boti effect. It also doesn't change to where you're going. Even when you close the doors. 

Video : https://vimeo.com/327912914

**Comment by Suffril** [comment]
You have two consoles in one room, so for a start, that's making this invalid. 
And it's not meant to change in flight, because your doors are meant to be closed, which is a bug in itself, but it's not a massive issue.
