### ISSUE TITLE
Tardis Console Offset When Viewed In From Outside

### ISSUE THREAD

**Issue by Ninja-Hinja42** [Spectre0987/TardisMod#248]
![2019-04-02_12 35 23](https://user-images.githubusercontent.com/36712216/55420040-16ca3b00-5544-11e9-8bd9-e56fc21c34c7.png)

mod version: 0.1.0b
forge version: 14.23.5.2815
in singleplayer, didn't check multiplayer

just opened the doors and noticed this.

**Comment by Spectre0987** [comment]
Fixed in 0.1.0C
