### ISSUE TITLE
Incorrect Block state when viewed from outside

### ISSUE THREAD

**Issue by Ninja-Hinja42** [Spectre0987/TardisMod#259]
View from outside of Tardis:
![2019-04-12_18 31 29](https://user-images.githubusercontent.com/36712216/56069552-8e247980-5d51-11e9-817b-c5bd0fb74086.png)
View from inside of Tardis:
![2019-04-12_18 31 37](https://user-images.githubusercontent.com/36712216/56069555-8f55a680-5d51-11e9-9d72-50e7e03e17cf.png)
mod version: 0.1.0c
forge version: 14.23.5.2815
Fences also appear to be disconnected from each other when viewing the tardis interior from the outside, and blocks with rotation are not rotated correctly.
![2019-04-12_18 42 46](https://user-images.githubusercontent.com/36712216/56069834-d42e0d00-5d52-11e9-9296-7d3ed3575a4a.png)
![2019-04-12_18 43 59](https://user-images.githubusercontent.com/36712216/56069856-f6c02600-5d52-11e9-9459-3842553379b0.png)
![2019-04-12_18 44 32](https://user-images.githubusercontent.com/36712216/56069885-16574e80-5d53-11e9-8d20-306ccd168aae.png)

**Comment by Spectre0987** [comment]
Fixed, will be in the next version
