### ISSUE TITLE
Crouching through the tardis door

### ISSUE THREAD

**Issue by Ninja-Hinja42** [Spectre0987/TardisMod#260]
If you sneak-walk through the tardis doors from the inside, you will pass through them instead of exiting the tardis.

![](https://media.giphy.com/media/OqJfMusU3uA1gYQXTR/giphy.gif)

**Comment by 50ap5ud5** [comment]
I believe the developers implemented that as an intended feature, so that you can view the SOTO (Smaller On the Outside) effect from different angles without being teleported out too easily.

**Comment by Spectre0987** [comment]
Exactly this.

**Comment by Ninja-Hinja42** [comment]
sorry

**Comment by Spectre0987** [comment]
No worries, thanks for your help in improving the mod!
