### ISSUE TITLE
BOTI is delayed

### ISSUE THREAD

**Issue by felker13** [Spectre0987/TardisMod#266]
When I open the TARDIS door, it takes a second or two for the interior to load. It would be better to keep the interior always loaded. It is possible with ChickenChunks, and it works well with 0.0.8, but the latest version of tardis mod does not work with that.
![Unloaded](https://user-images.githubusercontent.com/26328308/56760903-76f77a00-679c-11e9-9fb8-868e5e9591fd.png)

**Comment by 50ap5ud5** [comment]
Hi, just so you know, the Tardis interior dimension has been coded to always load your interior chunks, so external mods are not needed in this case. The slight delay in the BOTI render is also a known issue, so you aren't the only one experiencing this.

**Comment by felker13** [comment]
"the Tardis interior dimension has been coded to always load your interior chunks" Does it mean that the interior chunks are loaded every time I open the door or they are never unloaded? In the previous versions I experienced this issue only when I moved so far from the tardis exterior that it was unloaded. When I just closed the door and opened it immediately, this did not happen. I needed the external mod because I moved the interior door, and once the interior chunks were unloaded, they were reloaded only when I entered the tardis, but before that I could not see the interior from outside at all. As the mod does not let the interior to be unloaded, everything works well in version 0.0.8, but I would like to upgrade to the latest version.

**Comment by 50ap5ud5** [comment]
That is interesting. However the more technical reason behind this is something best suited for the developers to answer and not for me say.

**Comment by Spectre0987** [comment]
The delay is there for performance reasons

**Comment by felker13** [comment]
How can I disable that delay in the code? Or could you make a setting for that? Currently I am using my own version based on 0.0.8A. I fixed some bugs, readded real world flight you had removed before, and created my own jar file.  I would really like to update to the newer version, but this delay annoys me too much. I do not feel that it is bigger on the inside, I feel that I see a video broadcasted by a camera from an other point of the world. I know that is the truth, but I would like to feel that it is bigger on the inside.

**Comment by Swirtzly** [comment]
The newer versions make this work a lot better. Perhaps instead of creating your own build and stuff of the like, you could make a pull request to the GitHub for things you fix?

**Comment by felker13** [comment]
Sometimes I try the latest version. I tried version 0.1.0E on Saturday, but still experience the delay.
