### ISSUE TITLE
Tardis exterior is fading when I leave the tardis

### ISSUE THREAD

**Issue by felker13** [Spectre0987/TardisMod#267]
When I travel somewhere with the tardis and then I leave it, I see the exterior fading as shown below:
![fading](https://user-images.githubusercontent.com/26328308/56761835-a0b1a080-679e-11e9-80d5-61550515958a.png)

**Comment by 50ap5ud5** [comment]
Hi, this is a known issue. However, thanks for reporting it!

**Comment by Spectre0987** [comment]
Fixed in 0.1.0D
