### ISSUE TITLE
Invasion Cybermen are invisible. (Fixed, please close)

### ISSUE THREAD

**Issue by MishaPlayer** [Spectre0987/TardisMod#269]
Not sure what else to put here, so here's a screenshot of me using WAILA to show where the spy is.
![2019-04-28_15 52 31](https://user-images.githubusercontent.com/35854740/56869568-384a0580-69d0-11e9-88a9-8167cd34aef5.png)

EDIT: before asking about the log, I checked and it doesn't say anything about the cybermen,

Version: 0.1.0c
WAILA, Handles, Regen
Singleplayer

**Comment by Spectre0987** [comment]
Are you using Optifine or any other performance mod?

**Comment by MishaPlayer** [comment]
I encountered this bug using Surge and FoamFix, but tested in Creative (As seen in screenshot) using WAILIA (to reveal) Handles and Regen

**Comment by Herodegon** [comment]
Having the same issue while using the Offical New Tardis Modpack:
[https://minecraft.curseforge.com/projects/the-official-tardis-modpack](url)
![2019-04-29_10 23 19](https://user-images.githubusercontent.com/50110137/56902815-0e90ed00-6a69-11e9-8818-f58994066386.png)

**Comment by Spectre0987** [comment]
Thanks for reporting this!

**Comment by MishaPlayer** [comment]
v b bnn,
