### ISSUE TITLE
[feature request] add addable rooms like last mod

### ISSUE THREAD

**Issue by An0nym0us44** [Spectre0987/TardisMod#272]
I really loved how customization you can make your tardis in the last mod and I would love for it to be brought back.  It's just so simple and I don't want to spend time building humongous bases for modded and the addable rooms just solve that.

**Comment by Redstoneguy129** [comment]
This used to be a feature in a really old version of this mod but it was removed

**Comment by ProsperCraft** [comment]
The self-expanding rooms in the old TARDIS mod was one of the features players loved.  You would just click on the roundel with the sonic and select the room type and it would grow.

**Comment by Hax02** [comment]
Absolutely true, the old TARDIS mod was a great mod and this could be even greater, but the rooms are just better the old way.
