### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by TheGallifreyanKnight** [Spectre0987/TardisMod#273]
Add the master as a boss and please add more gallifreyan tools and weapons like the time lord staser and the master's laser screwdriver and please make the tardis demat and remat animations more realistic.  And the sound effects too.

**Comment by CommandrMoose** [comment]
1) http://punkproject.xyz/index is a better place to suggest things. 
2) How can we make them more realistic when it's based on something that isn't real?

**Comment by TheGallifreyanKnight** [comment]
Idk I guess improve animations and sound effects is what I mean.

**Comment by Suffril** [comment]
This issue quite frankly isn't a issue.
