### ISSUE TITLE
Can't get in TARDIS

### ISSUE THREAD

**Issue by QuicksilverBou** [Spectre0987/TardisMod#274]
I just travel to some destanation and I has been teleport out of Tardis. Now I can't get in.
Also two Tardis...
![2019-05-12_16 58 29](https://user-images.githubusercontent.com/35933010/57583384-91d62800-74d8-11e9-83b9-77aa1f89033e.png)

Mod Version: tardis-0.1.0D

**Comment by Spectre0987** [comment]
You likely destroyed your dimensional dams. Craft a Time Vector Generator and right click the exterior with it. Dupes are an unfortunate bug, and sadly one that has no fix.

**Comment by QuicksilverBou** [comment]
Well, It partly worked. Tardis also dupes in to self.

**Comment by Spectre0987** [comment]
That means you broke the Thermocouplings. See http://www.tardis-mod.com

**Comment by QuicksilverBou** [comment]
Yeah, I got it. I had use Time Vector Generator, but I stil can't open doors to come in. I had use `/tardis interior` command to get in.
Bug consist whith creating false tardis where real tardis inside self. I can't enter in "fake" tardis.
Unfortunately this bug is unfixuble as you say.
