### ISSUE TITLE
Door Gitch

### ISSUE THREAD

**Issue by QuicksilverBou** [Spectre0987/TardisMod#275]
Some time Tardis door looks glitchy...
![2019-05-15_23 12 52](https://user-images.githubusercontent.com/35933010/57806389-ae3bc400-7767-11e9-9571-3276a3a9e154.png)
![2019-05-12_20 57 57](https://user-images.githubusercontent.com/35933010/57806428-cad7fc00-7767-11e9-8b36-1f74101301f9.png)

**Comment by Spectre0987** [comment]
This came from our old modeler refusing to fix them. WIll be fixed in 1.13 re-write
