### ISSUE TITLE
Can't exit TARDIS!!!

### ISSUE THREAD

**Issue by RailfanReaper** [Spectre0987/TardisMod#288]
I've seen several other people have issues with this on Discord and Youtube. When it happens to me, it's usually pretty specific. I turn the stabilizers on mid-flight because I keep forgetting to turn them on (I checked the monitor to make sure I had all systems at 100%). When I turned them on, I was still in manual flight mode, where you have to run around and click the right buttons and stuff. I landed, and when I stepped out the door, I got teleported inside my TARDIS. It definitely moved, because when the doors were open, the landscape was different. I didn't change dimensions, either. After I tried to exit, I tried exiting again. This time, the doors didn't teleport me. I walked into the open doors, and I wasn't teleported or anything.

EDIT: This is for the latest version, 0.1.0D I'm using the Regeneration Mod, too.

EDIT 2: So I did some researching on the wiki, and I discovered that Real World Flight Mode is a bit glitchy, creating a dupe TARDIS and preventing you from exiting your TARDIS. I didn't use Real World mode, so that adds to my confusion. :confused:

**Comment by Spectre0987** [comment]
Take off and fly again, if that doesn't work, make sure that the monitor isn't blank

**Comment by ProsperCraft** [comment]
I can't get out of my door - 

https://gyazo.com/85f6077c0bc4b1774825053e68b37fe2

At first, I went through and it would teleport me back to my console, then I moved three times, and turned it around once, then the console was just a console could not interact with buttons, I relogged, the buttons worked again, but now the door would not work at all.

**Comment by ProsperCraft** [comment]
I tried free flight mode shift clicking on telepathics a few times, each time failed, then once it did work I see this now - 
![2019-06-24_20 36 08](https://user-images.githubusercontent.com/4427684/60065087-e10a9d80-96bf-11e9-879b-afae4d630865.png)

Two of me.

**Comment by ProsperCraft** [comment]
I was able to fly out the door, and once I landed and went back in with shift, my door was now gone.

**Comment by 50ap5ud5** [comment]
I don't believe using the "free flight mode" (Real World Flight) can help. Using it in 0.1.0D causes a known duplication bug similar to the one you experienced.

To fix the duplicate issue in your screenshot, you can try removing your dimensional dams. This will kick you out of the interior and prevent you from being teleported back inside the interior. 
Then, relog.
When you are logged in, use the /setblock command to delete the duplicate exterior. (remove both top and bottom blocks of the exterior
Reinstall the dimensional dams by right clicking on the exterior with a Time Vector Generator.
Use the /tardis interior command to access your interior.

If you are still unable to exit the Tardis, you may need to resort to using the /tardis remove command to disconnect the interior from the exterior, removing the old exterior using the /setblock command and growing a new Tardis with a Tardis coral.

**Comment by Spectre0987** [comment]
Yeah, if you've used the Real World Flight the only fix is to delete your entire player data

**Comment by litjohn50** [comment]
I am having the similar issues. And would appreciate a patch soon. Can't get out of my Tardis no matter what. Every time I walk out it get teleported back in with the purple particles, (same thing when I do /tardis exterior) once I get stuck inside the command won't work anymore. 

(Ps. Random speed buff don't know if that has anything to do with it)

Massive Duplications https://cdn.discordapp.com/attachments/554483756694765588/593140685419446314/unknown.png

https://gyazo.com/bc560c8281df52d7925ea93292b79929

Normal Players won't have access to the so far fixes. Looking forward for the patch

Will probably be rollingback to when RWF was first released version (didn't have this issue then).

**Comment by ProsperCraft** [comment]
Rolling back to pre- Real World Flight is not possible, it is back too far and would lose protections and many bugfixes.

**Comment by Spectre0987** [comment]
The _only_ way to fix that is to delete the player data
