### ISSUE TITLE
Dedicated Server crashlooping when placing a celestial compass in a TARDIS 

### ISSUE THREAD

**Issue by ProsperCraft** [Spectre0987/TardisMod#289]
https://github.com/Lumaceon/ClockworkPhase/issues/20

Goshen: -- Block entity being ticked --
  Name: tardis:tileentitydoorcc // net.tardis.mod.common.tileentity.exteriors.TileEntityDoorCC

**Comment by Swirtzly** [comment]
Is this still a problem?

**Comment by ProsperCraft** [comment]
Resolved thank you.
