### ISSUE TITLE
[Feature Request] Recall block to bring your TARDIS when you die and get sent to spawn.

### ISSUE THREAD

**Issue by ProsperCraft** [Spectre0987/TardisMod#290]
The largest point of frustration with the players of my DrTARDIS 2 modpack is when they die and get sent back to spawn, the old TARDIS mod had a block you could make with vanilla materials to recall it back to you, but this doesn't seem to have anything like this other then the remote which would have to have been bound and stashed carefully at the spawn of each world.

Please add a buildable recall block that could be created to recall your TARDIS if lost, or...make beds in the TARDIS work and trump all other respawns.

**Comment by Spectre0987** [comment]
You can craft a key with the remote to bind it

**Comment by ProsperCraft** [comment]
So craft a remote, and a key, then craft them together, and it will recall your TARDIS?

**Comment by Spectre0987** [comment]
Yeah
