### ISSUE TITLE
[Feature Request] Let admins bypass the forced teleport back to your own TARDIS

### ISSUE THREAD

**Issue by ProsperCraft** [Spectre0987/TardisMod#292]
When an admin types /tardis interior name it should not force them back to their own TARDIS.

**Comment by 50ap5ud5** [comment]
What are the issues you are experiencing that is causing your frustration? 

The /tardis interior is designed to teleport the command's executor to their Tardis interior. If you need to teleport to another player's Tardis, you can add a username parameter as shown in the wiki. (/tardis interior [Username])

Wiki article: https://tardis-mod.com/books/commands

**Comment by Spectre0987** [comment]
Note that this only works if you're outside the TARDIS to start with

**Comment by ProsperCraft** [comment]
no /tardis interior name sent me to their TARDIS, then forced me back to mine.

What I suggest is that /tardis interior sets their interior as your current allowed interior so it doesn't force you back to your own.

**Comment by Spectre0987** [comment]
Yeah, that's a bug. If you want it to work in your version though, exit the tardis first

**Comment by Spectre0987** [comment]
I'll fix this tomorrow

**Comment by Spectre0987** [comment]
Fixed in the next version
