### ISSUE TITLE
Client crash - NPE - tileEntityTardis.transferPlayer

### ISSUE THREAD

**Issue by ProsperCraft** [Spectre0987/TardisMod#296]
https://gist.github.com/ProsperCraft/d9d753fa81acb764e58be65343fd43f1

The player pulled out his thermocouple to repair it which lead to a TARDIS exterior in his control room, then he put it back in, and was flying he had his stabilizer off because he forgot to re-enable it after he repaired that component as well, and ran out of energy there was  explosion a the console then he crashed.

**Comment by Spectre0987** [comment]
This should be fixed in 0.1.0E (Now released)

**Comment by ProsperCraft** [comment]
Updated DrTARIDS 2 thank you.
