### ISSUE TITLE
Modpack keeps crashing

### ISSUE THREAD

**Issue by Jb503** [Spectre0987/TardisMod#306]
Version alpha 0.1.0E
Location starting
Installed mods https://gyazo.com/48deae87c68034f4d6b811cf3b3570d6 https://gyazo.com/d996abe9a36e62480f8d588a1ce64611 https://gyazo.com/48deae87c68034f4d6b811cf3b3570d6
[2019-07-14-5.log.gz](https://github.com/Spectre0987/TardisMod/files/3390597/2019-07-14-5.log.gz)

when i start it it works without tardis mod but when i add it it dont work

**Comment by Swirtzly** [comment]
Change Dimension IDs in the config. 

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered
```

**Comment by Jb503** [comment]
where is the notepad to change it
