### ISSUE TITLE
Mod conflict with Ice and Fire

### ISSUE THREAD

**Issue by Keltas** [Spectre0987/TardisMod#307]
When I enter Tardis the internal server seems to stop responding. I cannot interact with blocks, cannot drop items, the game freezes completely when trying to save and exit until I use task manager to force it to close. I have this issue while having following mods installed: 
iceandfire-1.7.1-1.12.2.jar,
jei_1.12.2-4.15.0.287.jar,
llibrary-1.7.19-1.12.2.jar,
tardis-0.1.0E.jar.
This is the log (there is no crash report as I am forced to use task manager to quit): https://pastebin.com/Q7DMzJ66
Steps to reproduce:

    Install Tardis mod together with Ice and Fire (plus JEI for convenience).
    Give yourself Tardis coral and plant it on the ground.
    While looking at it type "/tardis grow".
    Right click on the door of tardis with the key.
    Walk inside.
    The interior should generate but you cannot close the doors or walk back outside. When exiting the game it freezes.

**Comment by Spectre0987** [comment]
Could we have the debug log please?

**Comment by Keltas** [comment]
I've used "/debug start" and entered the Tardis however once the bug occurred the game did not react to "/debug stop". Exiting via task manager did not generate the debug log and normal exiting simply freezes and makes java stop responding.

**Comment by Swirtzly** [comment]
Let me give you a rundown on how to get a decent log of this situation
What you want to do, is:

1. Open the game
2. Replicate Error
3. Game will hang/crash like you describe
4. Close game or let it close itself
5. Navigate to logs folder ASAP after, and attach the file called ``latest.log``

**Comment by Keltas** [comment]
I've attached the log file in my first post it is: https://pastebin.com/Q7DMzJ66 .
This is the full log file after trying to get debug log: https://pastebin.com/PELtRQ7R

**Comment by Swirtzly** [comment]
Hmm, this is rather odd, as nothing is useful in these logs
I'm not actually sure if a ``debug.log`` generates outside a IDE, but I'll look into that later, as it's just gotten past midnight where I live

Could you check if this happens with the Tardis Mod on it's own?

**Comment by Keltas** [comment]
Once I remove Ice and Fire, Tardis mod on its own works without problems.

**Comment by Boromirkane** [comment]
Perhaps it's the monitor rendering bad things again. Perhaps add a compatibility friendly config option to disable the monitor rendering.

**Comment by Spectre0987** [comment]
Considering that that's one of the most important features of the mod.. no. If it doesn't work you'll just have to pick

**Comment by Spectre0987** [comment]
Yup, just checked in a dev enviroment, nothing shows up, so there's nothing I can do
