### ISSUE TITLE
[Feature requests] Extra things to add/fix.

### ISSUE THREAD

**Issue by josh-65** [Spectre0987/TardisMod#309]
- [ ] 1. Allow blocking certain dimensions.
- [ ] 2. Show when controls are pressed or in a position.
- [ ] 3. Allow changing how fast artron energy and the sub-system components goes down in the config.
- [ ] 4. Allow seeing Artron energy, Dimension and Location of the tardis on the console.
- [ ] 5. Allow turning off the "Optifine detected" screen.
- [ ] 6. Auto close the door when going in flight.
- [ ] 7. Fix being able to walk/hit buttons through the console.
- [ ] 8. Add some tardis decoration blocks.
- [ ] 9. A non land mode so I can fly for as long as I want.
- [ ] 10. Being able to enter coordinates into the telepathic linker on the console.
- [ ] 11. The hellbent monitor should be on the block not 1.5 blocks away.
- [ ] 12. Add support to make the tardis go crazy when trying to go to the trenzalore dimension from other mods.
- [ ] 13. Add the ability to change how much the camera shakes.
- [ ] 14. Add a text border as long dimensions name go off the hellbent monitor and have floating text.

**Comment by boot2big** [comment]
5 and 10 might not get added

**Comment by Spectre0987** [comment]
Literally all of these are either already a thing or a bad idea

**Comment by josh-65** [comment]
I get how some could be a bad idea but how are all these a thing in already I carnt find any of them in the mod.

**Comment by Spectre0987** [comment]
1. Allow blocking certain dimensions. | There's an interface, a whitelist, and a blacklist, what more do you want?

**Comment by Spectre0987** [comment]
The other stuff is stuff we may add to the 1.14 version, or stuff I'm not interested in adding

**Comment by josh-65** [comment]
Does it block them for all players and where is it?

**Comment by Spectre0987** [comment]
In the config file or the mod options, just like every other mod. And it's global, it affects everyone

**Comment by josh-65** [comment]
Ok thanks but will some of the things get added for the 1.12.2 version.

**Comment by Spectre0987** [comment]
No
