### ISSUE TITLE
Random error causing the server to crash.

### ISSUE THREAD

**Issue by josh-65** [Spectre0987/TardisMod#310]
There was a critical exception handling a packet on channel tardisio.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(1) exceeds writerIndex(4): UnpooledSlicedByteBuf(ridx: 4, widx: 4, cap: 4/4, unwrapped: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 5, cap: 256))

Im using minecraft 1.12.2 and tardis mod 1.0E hotfix.

[latest.log](https://github.com/Spectre0987/TardisMod/files/3457977/latest.log)

**Comment by josh-65** [comment]
It was the weeping angel mod.

**Comment by Swirtzly** [comment]
This cannot be correct, as the weeping angels mod does not use packets that would trigger this

**Comment by josh-65** [comment]
Well it stopped happening after i took out that mod.

**Comment by Swirtzly** [comment]
That doesn't mean, that that mod was the issue
