### ISSUE TITLE
Crash when enter tardis (load dimension) when used with OTG Biome Bundle

### ISSUE THREAD

**Issue by Boromirkane** [Spectre0987/TardisMod#311]
Crash when enter tardis (load dimension) when used with OTG Biome Bundle. 1.12.2.

I have deduced these 2 mods do not play nice together. The Dalek Mod however works with Biome Bundle. 

Breakdown of how I produced the bug. I creative I planted a tardis coral. It grew into a weird looking tardis. Broke the coral off around it, opened the door and entered. The dimension loaded for a split second (I saw the console) (btw I disabled the Bigger than inside feature. ) then the screen warped and it crashed. 

Happens every time. 
I used the latest version Tardis 0.1.0E
Biome Bundle 1.12.2 v61
forgemultipart 2.6.1.81

**Comment by 50ap5ud5** [comment]
Hi, thanks for reporting this. Could you please include the crash report file so that it can better clarify the more technical details?

**Comment by Boromirkane** [comment]
Of course, I will reproduce the bug. Bare with me...

**Comment by Boromirkane** [comment]
[crash-2019-08-05_22.41.56-client.txt](https://github.com/Spectre0987/TardisMod/files/3469518/crash-2019-08-05_22.41.56-client.txt)

**Comment by Spectre0987** [comment]
The game explicitly states that Optifine is **_not_** supported

**Comment by Boromirkane** [comment]
It states that with regards to bigger on the inside feature. I disabled that feature. I'll try it without optifine

**Comment by Boromirkane** [comment]
[crash-2019-08-05_23.38.43-client.txt](https://github.com/Spectre0987/TardisMod/files/3469624/crash-2019-08-05_23.38.43-client.txt)

**Comment by Boromirkane** [comment]
Here you go, same bug without optifine. Re-open please :)

**Comment by Swirtzly** [comment]
I would re-open this, because I know what the cause is, but I will instead, leave this issue open here #313 and deal with it there :)
