### ISSUE TITLE
Sonic Blaster Crash

### ISSUE THREAD

**Issue by Hawkfang42** [Spectre0987/TardisMod#314]
I used the sonic blaster in a temple then it crashed, here is the report:
---- Minecraft Crash Report ----
WARNING: coremods are present:
  Regeneration (Regeneration-1.12.2-1.8.1.jar)
Contact their authors BEFORE contacting forge
// You're mean.
Time: 8/5/19 6:46 PM
Description: Unexpected error
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=type, clazz=class net.minecraft.block.BlockSandStone$EnumType, values=[sandstone, chiseled_sandstone, smooth_sandstone]} as it does not exist in BlockStateContainer{block=minecraft:stained_hardened_clay, properties=[color]}
 at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
 at net.minecraft.block.BlockSandStone.func_176201_c(SourceFile:49)
 at net.minecraft.block.Block.getHarvestTool(Block.java:2057)
 at net.minecraftforge.common.ForgeHooks.canHarvestBlock(ForgeHooks.java:225)
 at net.minecraftforge.event.world.BlockEvent$BreakEvent.<init>(BlockEvent.java:128)
 at net.tardis.mod.common.items.ItemSonicBlaster.func_180614_a(ItemSonicBlaster.java:64)
 at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
 at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:467)
 at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
 at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
 at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
 at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
 at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
 at net.minecraft.client.main.Main.main(SourceFile:123)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Client thread
Stacktrace:
 at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
 at net.minecraft.block.BlockSandStone.func_176201_c(SourceFile:49)
 at net.minecraft.block.Block.getHarvestTool(Block.java:2057)
 at net.minecraftforge.common.ForgeHooks.canHarvestBlock(ForgeHooks.java:225)
 at net.minecraftforge.event.world.BlockEvent$BreakEvent.<init>(BlockEvent.java:128)
 at net.tardis.mod.common.items.ItemSonicBlaster.func_180614_a(ItemSonicBlaster.java:64)
 at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
 at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:467)
 at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579)
 at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
 at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
-- Affected level --
Details:
 Level name: MpServer
 All players: 1 total; [EntityPlayerSP['Hawkfang42'/615, l='MpServer', x=-150.70, y=65.00, z=890.43]]
 Chunk stats: MultiplayerChunkCache: 240, 240
 Level seed: 0
 Level generator: ID 00 - default, ver 1. Features enabled: false
 Level generator options: 
 Level spawn location: World: (176,64,256), Chunk: (at 0,4,0 in 11,16; contains blocks 176,0,256 to 191,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
 Level time: 29017 game time, 29017 day time
 Level dimension: 0
 Level storage version: 0x00000 - Unknown?
 Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
 Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
 Forced entities: 89 total; [EntitySkeleton['Skeleton'/13312, l='MpServer', x=-167.51, y=55.00, z=921.71], EntityItem['item.tile.stonebrick'/14595, l='MpServer', x=-154.88, y=48.00, z=887.90], EntityItem['item.tile.stonebrick'/14598, l='MpServer', x=-152.64, y=48.00, z=885.77], EntityItem['item.tile.stone.diorite'/14599, l='MpServer', x=-154.39, y=51.00, z=886.80], EntityItem['item.tile.stone.diorite'/14600, l='MpServer', x=-152.65, y=48.00, z=885.34], EntitySpider['Spider'/15121, l='MpServer', x=-167.50, y=25.00, z=899.50], EntityItem['item.tile.stonebrick'/14623, l='MpServer', x=-152.97, y=47.00, z=893.41], EntityItem['item.tile.stonebrick'/14624, l='MpServer', x=-151.08, y=48.00, z=894.29], EntityItem['item.tile.stonebrick'/14626, l='MpServer', x=-152.43, y=47.00, z=894.51], EntitySkeleton['Skeleton'/13607, l='MpServer', x=-184.50, y=22.00, z=888.50], EntityItem['item.item.rottenFlesh'/14636, l='MpServer', x=-148.10, y=48.00, z=890.60], EntitySheep['Sheep'/13613, l='MpServer', x=-78.50, y=64.00, z=969.50], EntitySheep['Sheep'/13615, l='MpServer', x=-81.37, y=64.00, z=960.79], EntityItem['item.item.bone'/14640, l='MpServer', x=-148.01, y=48.00, z=890.55], EntityBat['Bat'/14898, l='MpServer', x=-184.25, y=35.10, z=894.25], EntityBat['Bat'/15155, l='MpServer', x=-156.25, y=21.10, z=904.25], EntityBat['Bat'/15156, l='MpServer', x=-160.25, y=22.10, z=901.39], EntityBat['Bat'/15164, l='MpServer', x=-187.36, y=47.96, z=871.20], EntityBat['Bat'/15165, l='MpServer', x=-185.21, y=46.03, z=874.79], EntityItem['item.item.spiderEye'/14655, l='MpServer', x=-147.95, y=48.00, z=890.42], EntitySkeleton['Skeleton'/13897, l='MpServer', x=-91.50, y=27.00, z=918.50], EntityRabbit['Rabbit'/13134, l='MpServer', x=-168.17, y=64.00, z=902.98], EntityRabbit['Rabbit'/13135, l='MpServer', x=-169.49, y=68.00, z=885.63], EntityPlayerSP['Hawkfang42'/615, l='MpServer', x=-150.70, y=65.00, z=890.43], EntityRabbit['Rabbit'/13137, l='MpServer', x=-176.55, y=70.00, z=868.64], EntityRabbit['Rabbit'/13138, l='MpServer', x=-172.51, y=67.00, z=892.53], EntityCybermanInvasion['Invasion Cyberman'/14934, l='MpServer', x=-150.50, y=41.00, z=960.50], EntityZombie['Zombie'/14935, l='MpServer', x=-148.50, y=41.00, z=960.50], EntityRabbit['Rabbit'/13144, l='MpServer', x=-170.26, y=69.21, z=870.96], EntityZombie['Zombie'/14936, l='MpServer', x=-148.50, y=41.00, z=959.50], EntityRabbit['Rabbit'/13145, l='MpServer', x=-149.67, y=68.00, z=871.46], EntityCow['Cow'/13146, l='MpServer', x=-166.78, y=64.00, z=935.50], EntityCow['Cow'/13147, l='MpServer', x=-174.50, y=64.00, z=934.50], EntityCow['Cow'/13148, l='MpServer', x=-172.50, y=63.00, z=934.50], EntityCow['Cow'/13149, l='MpServer', x=-172.50, y=63.00, z=934.50], EntityEnderman['Enderman'/15207, l='MpServer', x=-190.50, y=53.00, z=893.50], EntitySkeleton['Skeleton'/15463, l='MpServer', x=-166.50, y=51.00, z=956.50], EntityZombie['Zombie'/15465, l='MpServer', x=-162.50, y=51.00, z=957.50], EntitySkeleton['Skeleton'/15210, l='MpServer', x=-166.50, y=46.00, z=958.50], EntityCreeper['Creeper'/15466, l='MpServer', x=-168.50, y=51.00, z=951.50], EntityCreeper['Creeper'/15211, l='MpServer', x=-160.50, y=46.00, z=955.50], EntityCreeper['Creeper'/15467, l='MpServer', x=-171.50, y=51.00, z=958.17], EntityCreeper['Creeper'/15212, l='MpServer', x=-159.50, y=46.00, z=955.50], EntityItem['item.item.enchantedBook'/14708, l='MpServer', x=-148.12, y=48.00, z=890.53], EntityItem['item.item.horsearmormetal'/14712, l='MpServer', x=-148.13, y=48.00, z=890.54], EntityItem['item.tile.chest'/14715, l='MpServer', x=-147.94, y=48.00, z=890.57], EntityCow['Cow'/13180, l='MpServer', x=-187.50, y=65.00, z=921.50], EntityCow['Cow'/13181, l='MpServer', x=-188.50, y=65.00, z=921.50], EntityCow['Cow'/13182, l='MpServer', x=-187.50, y=65.00, z=922.50], EntityCow['Cow'/13183, l='MpServer', x=-186.35, y=65.00, z=920.81], EntityRabbit['Rabbit'/13194, l='MpServer', x=-202.50, y=67.00, z=910.50], EntityRabbit['Rabbit'/13195, l='MpServer', x=-203.50, y=66.00, z=914.50], EntityRabbit['Rabbit'/13196, l='MpServer', x=-202.50, y=66.00, z=916.50], EntitySheep['Sheep'/13455, l='MpServer', x=-70.50, y=71.00, z=927.50], EntityCow['Cow'/13203, l='MpServer', x=-162.50, y=64.00, z=960.50], EntityCow['Cow'/13204, l='MpServer', x=-166.20, y=63.00, z=958.48], EntityCow['Cow'/13205, l='MpServer', x=-157.50, y=64.00, z=959.50], EntityCow['Cow'/13206, l='MpServer', x=-158.50, y=64.00, z=962.50], EntityCow['Cow'/13210, l='MpServer', x=-148.50, y=64.00, z=959.50], EntityCow['Cow'/13211, l='MpServer', x=-146.50, y=64.00, z=963.50], EntityCow['Cow'/13212, l='MpServer', x=-148.50, y=64.00, z=964.50], EntityCow['Cow'/13213, l='MpServer', x=-149.50, y=64.00, z=966.50], EntityCreeper['Creeper'/14750, l='MpServer', x=-145.50, y=46.00, z=960.50], EntitySheep['Sheep'/13475, l='MpServer', x=-76.24, y=64.00, z=967.09], EntitySheep['Sheep'/13476, l='MpServer', x=-77.66, y=64.00, z=966.06], EntitySheep['Sheep'/13477, l='MpServer', x=-76.50, y=64.00, z=965.50], EntitySheep['Sheep'/13478, l='MpServer', x=-75.64, y=64.00, z=954.78], EntitySheep['Sheep'/13223, l='MpServer', x=-97.50, y=84.00, z=882.50], EntitySheep['Sheep'/13224, l='MpServer', x=-99.51, y=80.00, z=882.26], EntitySheep['Sheep'/13225, l='MpServer', x=-96.50, y=81.00, z=877.50], EntitySheep['Sheep'/13226, l='MpServer', x=-96.50, y=85.00, z=881.50], EntityRabbit['Rabbit'/13242, l='MpServer', x=-222.50, y=70.00, z=901.50], EntityRabbit['Rabbit'/13243, l='MpServer', x=-220.50, y=70.00, z=901.50], EntityRabbit['Rabbit'/13244, l='MpServer', x=-223.50, y=70.00, z=898.50], EntityRabbit['Rabbit'/13250, l='MpServer', x=-225.50, y=70.00, z=913.50], EntitySkeleton['Skeleton'/14789, l='MpServer', x=-161.70, y=46.00, z=955.30], EntitySkeleton['Skeleton'/14791, l='MpServer', x=-147.75, y=46.00, z=950.18], EntityRabbit['Rabbit'/13266, l='MpServer', x=-175.50, y=76.00, z=835.50], EntityRabbit['Rabbit'/13267, l='MpServer', x=-175.50, y=77.00, z=833.50], EntityItem['item.tile.stonebrick'/14549, l='MpServer', x=-147.13, y=49.00, z=885.13], EntityItem['item.tile.stonebrick'/14558, l='MpServer', x=-153.88, y=47.00, z=891.77], EntityRabbit['Rabbit'/13295, l='MpServer', x=-135.50, y=72.00, z=827.50], EntityRabbit['Rabbit'/13296, l='MpServer', x=-135.50, y=72.00, z=829.50], EntityRabbit['Rabbit'/13297, l='MpServer', x=-135.50, y=72.00, z=825.50], EntityItem['item.tile.stonebrick'/14585, l='MpServer', x=-154.83, y=47.00, z=889.58], EntityItem['item.tile.stonebrick'/14586, l='MpServer', x=-152.75, y=46.00, z=888.13], EntityItem['item.tile.stonebrick'/14587, l='MpServer', x=-155.88, y=47.00, z=889.81], EntityItem['item.tile.stonebrick'/14589, l='MpServer', x=-154.88, y=47.00, z=887.88], EntitySpider['Spider'/13310, l='MpServer', x=-162.70, y=52.00, z=913.92]]
 Retry entities: 0 total; []
 Server brand: fml,forge
 Server type: Integrated singleplayer server
Stacktrace:
 at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
 at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
 at net.minecraft.client.main.Main.main(SourceFile:123)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:497)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
-- System Details --
Details:
 Minecraft Version: 1.12.2
 Operating System: Windows 10 (amd64) version 10.0
 Java Version: 1.8.0_51, Oracle Corporation
 Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
 Memory: 398151392 bytes (379 MB) / 855638016 bytes (816 MB) up to 4294967296 bytes (4096 MB)
 JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
 IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
 FML: MCP 9.42 Powered by Forge 14.23.5.2838 6 mods loaded, 6 mods active
 States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
 | State  | ID           | Version      | Source                        | Signature                                |
 |:------ |:------------ |:------------ |:----------------------------- |:---------------------------------------- |
 | LCHIJA | minecraft    | 1.12.2       | minecraft.jar                 | None                                     |
 | LCHIJA | mcp          | 9.42         | minecraft.jar                 | None                                     |
 | LCHIJA | FML          | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
 | LCHIJA | forge        | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
 | LCHIJA | tardis       | 0.1.0E       | tardis-0.1.0E.jar             | None                                     |
 | LCHIJA | regeneration | 1.8.1        | Regeneration-1.12.2-1.8.1.jar | None                                     |
 Loaded coremods (and transformers): 
Regeneration (Regeneration-1.12.2-1.8.1.jar)
  me.swirtzly.regeneration.asm.RegenClassTransformer
 GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.0' Renderer: 'AMD Radeon HD 6530D'
 Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
 LWJGL: 2.9.4
 OpenGL: AMD Radeon HD 6530D GL version 4.5.13399 Compatibility Profile Context 15.201.1151.0, ATI Technologies Inc.
 GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.
 Using VBOs: Yes
 Is Modded: Definitely; Client brand changed to 'fml,forge'
 Type: Client (map_client.txt)
 Resource Packs: Amtrak+.zip, CD+najbrt+0.8.zip
 Current Language: English (US)
 Profiler Position: N/A (disabled)
 CPU: 4x AMD A6-3620 APU with Radeon(tm) HD Graphics

**Comment by Spectre0987** [comment]
Fixed in 0.1.1A
