### ISSUE TITLE
crash when rendering terrain in a new position

### ISSUE THREAD

**Issue by DintyGadget** [Spectre0987/TardisMod#316]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.226.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  BetterFontsCore (TTFR-1.12.1-1.9.1.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 8/9/19 5:08 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at net.minecraft.client.renderer.BlockModelRenderer.func_178264_a(BlockModelRenderer.java:501)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187495_a(BlockModelRenderer.java:466)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178266_a(BlockModelRenderer.java:492)
	at net.tardis.mod.client.worldshell.RenderWorldShell.renderWorldShell(RenderWorldShell.java:47)
	at net.tardis.mod.util.client.RenderHelper.renderPortal(RenderHelper.java:96)
	at net.tardis.mod.util.client.RenderHelper.renderPortal(RenderHelper.java:135)
	at net.tardis.mod.client.renderers.controls.RenderDoor.doRender(RenderDoor.java:75)
	at net.tardis.mod.client.renderers.controls.RenderDoor.func_76986_a(RenderDoor.java:24)
	at net.minecraft.client.renderer.entity.RenderManager.redirect$onRenderEntity$zzn000(RenderManager.java:680)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:839)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1927)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at launcher.lOlkEKchebureK.LoLkeKChEbUREk(SourceFile:330)
	at launcher.lOlkEKchebureK.main(SourceFile:210)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_178264_a(BlockModelRenderer.java:501)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187495_a(BlockModelRenderer.java:466)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178266_a(BlockModelRenderer.java:492)
	at net.tardis.mod.client.worldshell.RenderWorldShell.renderWorldShell(RenderWorldShell.java:47)
	at net.tardis.mod.util.client.RenderHelper.renderPortal(RenderHelper.java:96)
	at net.tardis.mod.util.client.RenderHelper.renderPortal(RenderHelper.java:135)
	at net.tardis.mod.client.renderers.controls.RenderDoor.doRender(RenderDoor.java:75)
	at net.tardis.mod.client.renderers.controls.RenderDoor.func_76986_a(RenderDoor.java:24)
	at net.minecraft.client.renderer.entity.RenderManager.redirect$onRenderEntity$zzn000(RenderManager.java:680)

-- Entity being rendered --
Details:
	Entity Type: tardis:tardis_door (net.tardis.mod.common.entities.controls.ControlDoor)
	Entity ID: 2406
	Entity Name: Door
	Entity's Exact location: 250.50, 129.00, 264.50
	Entity's Block location: World: (250,129,264), Chunk: (at 10,8,8 in 15,16; contains blocks 240,0,256 to 255,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.tardis.mod.client.renderers.controls.RenderDoor@5b1a6763
	Location: -9.11,1.50,-0.02 - World: (-10,1,-1), Chunk: (at 6,0,15 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: -90.0
	Delta: 0.44011974
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:412)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:392)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:839)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1927)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 1335081 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at launcher.lOlkEKchebureK.LoLkeKChEbUREk(SourceFile:330)
	at launcher.lOlkEKchebureK.main(SourceFile:210)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2951272712 bytes (2814 MB) / 6429081600 bytes (6131 MB) up to 6429081600 bytes (6131 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=ThisTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms6144M -Xmx6144M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:+DisableAttachMechanism
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 70 mods loaded, 70 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version                    | Source                                        | Signature                                |
	|:------ |:----------------------- |:-------------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2                     | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                     | 9.42                       | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                     | 8.0.99.99                  | forge.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                   | 14.23.5.2838               | forge.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore           |                            | minecraft.jar                                 | None                                     |
	| LCHIJA | betterfonts             | 1.9.1                      | minecraft.jar                                 | None                                     |
	| LCHIJA | openmodscore            | 0.12.2                     | minecraft.jar                                 | None                                     |
	| LCHIJA | ambientsounds           | 3.0                        | AmbientSounds_v3.0.9_mc1.12.2.jar             | None                                     |
	| LCHIJA | ctm                     | MC1.12.2-0.3.3.22          | CTM-MC1.12.2-0.3.3.22.jar                     | None                                     |
	| LCHIJA | appliedenergistics2     | rv6-stable-7               | appliedenergistics2-rv6-stable-7.jar          | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | architecturecraft       | @VERSION@                  | architecturecraft-1.12-3.98.jar               | None                                     |
	| LCHIJA | baubles                 | 1.5.2                      | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | forgelin                | 1.8.3                      | Forgelin-1.8.3.jar                            | None                                     |
	| LCHIJA | betterrecords           | 1.12.2-1.6.1               | BetterRecords-1.12.2-1.6.1.jar                | None                                     |
	| LCHIJA | buildcraftlib           | 7.99.24.2                  | buildcraft-all-7.99.24.2.jar                  | None                                     |
	| LCHIJA | buildcraftcore          | 7.99.24.2                  | buildcraft-all-7.99.24.2.jar                  | None                                     |
	| LCHIJA | buildcraftbuilders      | 7.99.24.2                  | buildcraft-all-7.99.24.2.jar                  | None                                     |
	| LCHIJA | buildcrafttransport     | 7.99.24.2                  | buildcraft-all-7.99.24.2.jar                  | None                                     |
	| LCHIJA | buildcraftsilicon       | 7.99.24.2                  | buildcraft-all-7.99.24.2.jar                  | None                                     |
	| LCHIJA | buildcraftcompat        | 7.99.24.2                  | buildcraft-all-7.99.24.2.jar                  | None                                     |
	| LCHIJA | buildcraftenergy        | 7.99.24.2                  | buildcraft-all-7.99.24.2.jar                  | None                                     |
	| LCHIJA | buildcraftfactory       | 7.99.24.2                  | buildcraft-all-7.99.24.2.jar                  | None                                     |
	| LCHIJA | buildcraftrobotics      | 7.99.24.2                  | buildcraft-all-7.99.24.2.jar                  | None                                     |
	| LCHIJA | chisel                  | MC1.12.2-0.2.1.35          | Chisel-MC1.12.2-0.2.1.35.jar                  | None                                     |
	| LCHIJA | codechickenlib          | 3.2.2.353                  | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | customnpcs              | 1.12                       | CustomNPCs_1.12.2(30Jan19).jar                | None                                     |
	| LCHIJA | ptrmodellib             | 1.0.4                      | PTRLib-1.0.4.jar                              | None                                     |
	| LCHIJA | props                   | 2.6.2                      | Decocraft-2.6.2_1.12.2.jar                    | None                                     |
	| LCHIJA | energyconverters        | 1.3.0.15                   | energyconverters_1.12.2-1.3.0.15.jar          | None                                     |
	| LCHIJA | ic2                     | 2.8.179-ex112              | industrialcraft-2-2.8.179-ex112.jar           | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | galacticraftcore        | 4.0.2.226                  | GalacticraftCore-1.12.2-4.0.2.226.jar         | None                                     |
	| LCHIJA | galacticraftplanets     | 4.0.2.226                  | Galacticraft-Planets-1.12.2-4.0.2.226.jar     | None                                     |
	| LCHIJA | mjrlegendslib           | 1.12.2-1.1.8               | MJRLegendsLib-1.12.2-1.1.8.jar                | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | extraplanets            | 1.12.2-0.5.5               | ExtraPlanets-1.12.2-0.5.5.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | forgemultipartcbe       | 2.6.1.81                   | ForgeMultipart-1.12.2-2.6.1.81-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe           | 2.6.1.81                   | ForgeMultipart-1.12.2-2.6.1.81-universal.jar  | None                                     |
	| LCHIJA | minecraftmultipartcbe   | 2.6.1.81                   | ForgeMultipart-1.12.2-2.6.1.81-universal.jar  | None                                     |
	| LCHIJA | gravisuite              | 3.1.1                      | Gravitation+Suite-3.1.1.jar                   | None                                     |
	| LCHIJA | jei                     | 4.15.0.287                 | jei_1.12.2-4.15.0.287.jar                     | None                                     |
	| LCHIJA | gregtech                | 1.8.4.419                  | gregtech-1.12.2-1.8.4.419.jar                 | None                                     |
	| LCHIJA | hardcoredarkness        | 2.0                        | HardcoreDarkness-MC1.12.2-2.0.jar             | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | harvest                 | 1.12-1.2.7-20              | Harvest-1.12-1.2.7-20.jar                     | None                                     |
	| LCHIJA | waila                   | 1.8.26                     | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LCHIJA | inventorytweaks         | 1.63+release.109.220f184   | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest               | 1.12.2-7.0.67.844          | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| LCHIJA | jeresources             | 0.9.2.60                   | JustEnoughResources-1.12.2-0.9.2.60.jar       | None                                     |
	| LCHIJA | malisiscore             | 1.12.2-6.5.1-SNAPSHOT      | malisiscore-1.12.2-6.5.1.jar                  | None                                     |
	| LCHIJA | malisisdoors            | 1.12.2-7.3.0               | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| LCHIJA | moreplayermodels        | 1.12.2                     | MorePlayerModels_1.12.2(18jan18).jar          | None                                     |
	| LCHIJA | mrtjpcore               | 2.1.4.43                   | MrTJPCore-1.12.2-2.1.4.43-universal.jar       | None                                     |
	| LCHIJA | openmods                | 0.12.2                     | OpenModsLib-1.12.2-0.12.2.jar                 | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks              | 1.8.1                      | OpenBlocks-1.12.2-1.8.1.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | planetprogression       | 1.12.2-0.3.7               | PlanetProgression-1.12.2-0.3.7.jar            | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | projectred-core         | 4.9.4.120                  | ProjectRed-1.12.2-4.9.4.120-Base.jar          | None                                     |
	| LCHIJA | projectred-compat       | 1.0                        | ProjectRed-1.12.2-4.9.4.120-compat.jar        | None                                     |
	| LCHIJA | projectred-integration  | 4.9.4.120                  | ProjectRed-1.12.2-4.9.4.120-integration.jar   | None                                     |
	| LCHIJA | projectred-transmission | 4.9.4.120                  | ProjectRed-1.12.2-4.9.4.120-integration.jar   | None                                     |
	| LCHIJA | projectred-illumination | 4.9.4.120                  | ProjectRed-1.12.2-4.9.4.120-lighting.jar      | None                                     |
	| LCHIJA | scp                     | 2.1.1                      | SCP+Lockdown-1.12.2-2.1.1-beta.jar            | None                                     |
	| LCHIJA | sgcraft                 | 1.13.2                     | SGCraft-1.3-mc1.12.2.jar                      | None                                     |
	| LCHIJA | soviet                  | 0.4 Creative Content Only! | Soviet+Lab+Mod-0.4+Creative+Content+Only!.jar | None                                     |
	| LCHIJA | tardis                  | 0.1.0E                     | tardis-0.1.0E.jar                             | None                                     |
	| LCHIJA | thaumcraft              | 6.1.BETA26                 | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
	| LCHIJA | thaumicjei              | 1.6.0                      | ThaumicJEI-1.12.2-1.6.0-27.jar                | None                                     |
	| LCHIJA | bspkrscore              | at_0.9                     | Treecapitator-1.12-at_0.9a.jar                | None                                     |
	| LCHIJA | treecapitator           | at_0.9                     | Treecapitator-1.12-at_0.9a.jar                | None                                     |
	| LCHIJA | wawla                   | 2.5.273                    | Wawla-1.12.2-2.5.273.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | xaerominimap            | 1.17.5                     | Xaeros_Minimap_1.17.5_Forge_1.12.jar          | None                                     |
	| LCHIJA | xaeroworldmap           | 1.4.7                      | XaerosWorldMap_1.4.7_Forge_1.12.jar           | None                                     |
	| LCHIJA | matteroverdrive         | 0.7.0.0                    | MatterOverdrive-1.12.2-0.7.1.0-universal.jar  | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.226.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
BetterFontsCore (TTFR-1.12.1-1.9.1.jar)
  cubex2.ttfr.BFClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 431.60' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.60, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 431.60
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Spectre0987** [comment]
Should be fixed in the next update
