### ISSUE TITLE
Crash when BOTI renders stargate

### ISSUE THREAD

**Issue by Witherking25** [Spectre0987/TardisMod#317]
i built a stargate from the stargate network mod in my tardis (don't ask me why) and when i left my tardis, my game crashed

**Comment by CommandrMoose** [comment]
We can't do anything without a crash log.

**Comment by Witherking25** [comment]
[crash-2019-08-09_19.14.15-client.txt](https://github.com/Spectre0987/TardisMod/files/3488426/crash-2019-08-09_19.14.15-client.txt)

**Comment by Spectre0987** [comment]
Unfortunately due do some mod's rendering weirdness, BOTI can't handle them. There's a patch coming out to fix most of these, and a way to stop the rest from rendering.
