### ISSUE TITLE
Game Soft Freezes upon entering the TARDIS

### ISSUE THREAD

**Issue by KingDomino** [Spectre0987/TardisMod#318]
Whenever I enter the TARDIS my game enters this state where I can walk around and navigate menus, break blocks, and do anything I want except for:

Interact with blocks via right-clicking (GUIs still show up if the block has one, and I can craft and smelt, but doors won't open/close, and the interior or console won't change when I select the option.

Leave the game or the TARDIS.

Upon clicking the leave game button the window stops responding and I have to force it to close, so I can't get a crash log. 

Walking out of the TARDIS door has no effect.

Log file: https://pastebin.com/Fu5R4Wtm

Crash log isn't created.

Edit: BOTI effect is disabled, the problem persists regardless of allocated RAM.

**Comment by Spectre0987** [comment]
Do you know what HammerCore is?

**Comment by Spectre0987** [comment]
Actually, what mods are you using from this list? https://www.curseforge.com/minecraft/mc-mods/hammer-lib/relations/dependents

**Comment by KingDomino** [comment]
That's 119 pages of mods... I'll just remove it and see what errors.

**Comment by Spectre0987** [comment]
Lol, sorry https://www.curseforge.com/minecraft/mc-mods/hammer-lib/relations/dependents?filter-related-dependents=3

**Comment by KingDomino** [comment]
I found it: Botanic Additions.

**Comment by KingDomino** [comment]
The problem still happens, even without Botanic Additions and HammerCore

**Comment by Spectre0987** [comment]
What's the log without those?

**Comment by Spectre0987** [comment]
[22:37:03] [Client thread/INFO]: Creating default SeasonInfo for dimension overworld
[22:37:04] [Client thread/INFO]: Setting weather renderer for dimension [overworld]

What mods do you have related to these?

**Comment by KingDomino** [comment]
I'll check, but it doesn't ring a bell.

**Comment by Spectre0987** [comment]
No weather / season mods? Also does a debug.log generate?

**Comment by KingDomino** [comment]
Where can I find a debug log? I've never needed one of those.

**Comment by Spectre0987** [comment]
Should be in the same directory as the latest.log, but it might not generate for you

**Comment by KingDomino** [comment]
Not there, sorry.

**Comment by Spectre0987** [comment]
Hey, could you try disabling Botania's custom sky render in their config please?

**Comment by KingDomino** [comment]
Sure, I'll try this when I get the chance.

**Comment by Spectre0987** [comment]
I figured it out, I'll get you have Fire and Ice don't you?

**Comment by KingDomino** [comment]
Yes, I have Fire and Ice.

**Comment by Spectre0987** [comment]
Alright, please report this to them, it's not on us
