### ISSUE TITLE
Monitor doesn't work.

### ISSUE THREAD

**Issue by tsl3161991** [Spectre0987/TardisMod#320]
For some reason, the monitor screen suddenly stopped working. It worked yesterday, but today it's completely blank and clicking on it doesn't do anything. Is there any way to fix it, or at least access the monitor a different way?

**Comment by Spectre0987** [comment]
This is an odd issue we're investigating. Try to grow another TARDIS to clear it up, or if you're on a server go into a different world and grow one, then join the other world
