### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by ThioBacca** [Spectre0987/TardisMod#325]
whilst playing around with opencomputers and handles mod. i tried materialising the tardis inside of the console room(m.setTardisDestination(272,128,259,2)command used)it did take off but landed in the overworld, on exit 2 tardis' appeared and i started riding one like a horse whilst it was looping the landing sound.
i think it may be some sort of remnant from the real world flight control.
i wasn't able to get any pictures but it also didnt crash

**Comment by Spectre0987** [comment]
That's... odd. The TARDIS dimension is obvoiusly blocked to TARDISes, so it would default to the overworld. And the duplication glitch is one I don't know how to fix honestly
