### ISSUE TITLE
(1.14) the picture on change interior is a bit low and hides the "Next" button option

### ISSUE THREAD

**Issue by ThioBacca** [Spectre0987/TardisMod#330]
![image](https://user-images.githubusercontent.com/38400400/79078194-7b46db00-7cfe-11ea-9681-8544a8d3760e.png)

**Comment by Spectre0987** [comment]
This issue doesn't occur on auto gui scale, we're looking into it

**Comment by Spectre0987** [comment]
Fixed in 6a6251e8, please move future issues to the 1.14
