### ISSUE TITLE
Screen goes white when i open the tardis doors

### ISSUE THREAD

**Issue by DigiWiz87** [Spectre0987/TardisMod#335]
I've just grown a tardis and go to open the doors but when i open them, the whole screen goes white

Expected Behaviour: TARDIS doors open and the screen behaves as normal

Steps to Reproduce: Grow a TARDIS and open the doors

Screenshot of the issue:
![Screenshot (260)](https://user-images.githubusercontent.com/53604844/82116893-c3757500-9764-11ea-8993-ecdae78b91e1.png)

**Comment by Swirtzly** [comment]
You not going to give a log or crash report?

**Comment by DigiWiz87** [comment]
i can't give a crash report cuz it doesn't crash the game, i'm just unable to do anything

**Comment by Swirtzly** [comment]
Perhaps you didn't see me reply to you on Discord. Go to the logs folder as soon as this happens. As then upload the latest.log file here

**Comment by DigiWiz87** [comment]
ok

**Comment by DigiWiz87** [comment]
[2020-05-16-1.log](https://github.com/Spectre0987/TardisMod/files/4638192/2020-05-16-1.log)
This is the most recent log

**Comment by Swirtzly** [comment]
OTG does not work well with TARDIS. You either need to remove it or move to 1.14. 1.12 is no longer recieving bug fixes.
