### ISSUE TITLE
Game Crashes When Interacting With Story Teller Villager

### ISSUE THREAD

**Issue by ArcticBear08** [Spectre0987/TardisMod#338]
Issue: For some reason, my game started to crash whenever right clicking the Story Teller Villager.
How to Replicate: Not entirely sure, as it seemed to happen out of nowhere.
List of Mods: 
![image](https://user-images.githubusercontent.com/70857102/92331847-12f6ee00-f03f-11ea-9acd-b68e233b4bbb.png)
Crash Reports: 
[crash-2020-09-06_12.35.43-client.txt](https://github.com/Spectre0987/TardisMod/files/5180046/crash-2020-09-06_12.35.43-client.txt)
[crash-2020-09-06_12.38.54-client.txt](https://github.com/Spectre0987/TardisMod/files/5180048/crash-2020-09-06_12.38.54-client.txt)

**Comment by Swirtzly** [comment]
https://gitlab.com/Spectre0987/TardisMod-1-14
