### ISSUE TITLE
[Suggestion] Crouching next to a TARDIS allows you to go with it when it takes off

### ISSUE THREAD

**Issue by VenWhoVian** [Spectre0987/TardisMod#339]
I think this would be a cool feature and you could add the feature that if you run at the TARDIS and crouch as it's taking off it crashes the TARDIS, just like captain jack did in the episode "Utopia". I could understand why you wouldn't add this feature as it could be used as a form of harassment and crashing your TARDIS would not be fun either, I just thought it could be neat.

**Comment by AngryScotishMan9** [comment]
1.12 isn't being updated anymore mate

**Comment by VenWhoVian** [comment]
Im such an idiot

**Comment by VenWhoVian** [comment]
I posted

**Comment by VenWhoVian** [comment]
in the wrong place
