### ISSUE TITLE
Doctor Who Episode Expansion

### ISSUE THREAD

**Issue by EnderTrekkie** [Spectre0987/TardisMod#341]
**Goal:**
To have Doctor Who episodes as part of the mod, namely that the player can save villages from Extraterrestrials

Details are in this design doc, please read and comment.
https://docs.google.com/document/d/1WZTbHj_WpjaZyFGKrz_iDfHCffqjGYXVCOGAlhmwv80/edit?usp=sharing

**Comment by Suff99** [comment]
Hello,
This Github is for the now-defunct 1.12 version, please use 
https://gitlab.com/Spectre0987/TardisMod-1-14/-/issues for future suggestions and issues.
