### ISSUE TITLE
Earthshock gun won't deal more damage!

### ISSUE THREAD

**Issue by Dzsikhaj** [Spectre0987/TardisMod#343]
The gun does the same damage, beside that, ever other thing works with it. It sets mobs on fire on high damage, consumes more fuel on each level, takes and gives back artron batteries and screwdrivers. Playing on the freshest realese straight from the curseforge page, 1.16.5 with about ~70 other mods, one of them being the regen mod. The regen mod might couse the trouble but I don't have the time to test it.

**Comment by Dzsikhaj** [comment]
Update! I've check the mod by itself, the issue still stands...

**Comment by Suff99** [comment]
https://gitlab.com/Spectre0987/TardisMod-1-14/-/issues/371
