### ISSUE TITLE
Refactoring compatibility

### ISSUE THREAD

**Issue by Jackiecrazy** [Spectre0987/TardisMod#42]
Just a heads up that the latest version of weeping angels has changed the name of its class from EntityAngel to EntityWeepingAngel, which breaks the compat and causes a CTD when both are loaded.

EDIT: oof, I see it's been fixed in git, but the changes are not compiled into 0.0.4 yet. Apologies then.

**Comment by ReallySub** [comment]
Yeah, I'm author of angels and help with this mod, so I fixed them at the same time this morning
