### ISSUE TITLE
Creating rooms in tardis can destroy exit doors and control room

### ISSUE THREAD

**Issue by alistairporter** [Spectre0987/TardisMod#47]

**Comment by SandedShoes** [comment]
@Spectre0987 I feel like we could fix this by blocking use of the remove within 16 blocks of the console/door or something similiar?

**Comment by alistairporter** [comment]
making the corridor templates longer than the length of the room should fix the issue, the provlem is that when you add a room to the side of a corridor, directly adjacent to the console room it intersects with the console room and in my case blocked access to the door.

**Comment by SandedShoes** [comment]
I feel like they're probably gonna be re-done at some point anyways

**Comment by SandedShoes** [comment]
Right now I'll be closing this, as this report was from a really old version

The room gen structures are being redone and the entire system behind them is being redone also 

If you feel that when this new system is done and you still have this issue, don't feel shy about making a new report about it 

Thank you!
