### ISSUE TITLE
Target 0.0.6 Features

### ISSUE THREAD

**Issue by Spectre0987** [Spectre0987/TardisMod#54]
- [x] Hellbent Interior.

- [x] Interior Doors as blocks.

- [ ] Console selection GUI

- [x] A way to remove current console room

- [ ] Hellbent corridors

- [x] Waypoints

**Comment by SandedShoes** [comment]
- [ ] Improve registry code so that they are all a bit more similiar to TItems
- [ ] Replace Spectres really bad, probably made when he was drunk, models
