### ISSUE TITLE
Tardis Corral Non-Fatal Crash

### ISSUE THREAD

**Issue by BrisingrAerowing** [Spectre0987/TardisMod#57]
[Crash Log](https://paste.dimdev.org/nuhifupefo.mccrash)

Happened while I was exploring after placing a Tardis Corral.

I have tried to place a Tardis from the creative search tab, but I can't figure out how to unlock it.

Version 0.0.5a.

**Comment by BrisingrAerowing** [comment]
No it hasn't. That line is due to VanillaFix.

**Comment by Spectre0987** [comment]
As to my question though, did you just place the TARDIS Coral on the ground from your inventory?

**Comment by BrisingrAerowing** [comment]
Yup. I placed it and went exploring. The issue happened about 5-6 minutes later.

**Comment by SandedShoes** [comment]
I looked into this today, from a slim over it, it seems to happen when the coral has grown and the player is not online, so it has no one to give the key to... 

But you way you speak, it sorta indicates single player so now I'm not so sure

I'll be taking a more in depth look at this tomorrow

**Comment by SandedShoes** [comment]
I fixed this :)
