### ISSUE TITLE
inventory screen crash

### ISSUE THREAD

**Issue by Iashar** [Spectre0987/TardisMod#66]
Likely my fault somehow, but references your mod.
Was opening my inventory after upgrading to the version released a day or 2 ago, and it crashes me to desktop if i open my inventory.
I did have some of the old stuff, the sonic and a key in my inventory.
Crashlog:
https://pastebin.com/PdiqDSsa

**Comment by SandedShoes** [comment]
Oh weird, that event class shouldn't even be firing. Rest assured, I'll have this fixed today and I'll have @Spectre0987 release the fix

Apologies

**Comment by Iashar** [comment]
Well that was quick! Got it fixed on your end already? :)

**Comment by SandedShoes** [comment]
Yeah, whether @Spectre0987 decides to release this, is up to him lmao
