### ISSUE TITLE
Sometimes the TARDIS interior will appear in the cave of a moon from adv. rocketry

### ISSUE THREAD

**Issue by HighwayStar54** [Spectre0987/TardisMod#74]
Title. I'll add some screenshots if I am able to reproduce, but the tardis interior once created in a moon biome in advanced rocketry, with lowgravity and all. (I dug out and checked).

**Comment by Spectre0987** [comment]
Are you using Optifine?

**Comment by HighwayStar54** [comment]
Yes, actually, but I don't think that would affect worldgen

**Comment by Spectre0987** [comment]
The interior isn't really there. It's the bigger on the inside effect.

**Comment by HighwayStar54** [comment]
Yeah, but when you enter the Tardis aren't you supposed to be in another dimension?

**Comment by SandedShoes** [comment]
There is no world gen involved if this is what I think you're referring to.

We render the exterior and the interior outside the tardis, and then essentially cookie cut out the irrelevant parts. The tardis interior, is indeed, in a different dimension. 

Optifine doesn't like this and decides to render the entire thing, breaking the effect. I've been meaning to look into seeing if there is a fix but this is probably unlikely.. 


I can only suggest to you to find another better performance mod, perhaps BetterFPS?

**Comment by HighwayStar54** [comment]
I do have BOTI rendering problems but this is not what I'm referring to. When I enter the tardis, the biome is something  from advanced rocketry moons(instead of "The Void"), can't remember what it's called. If I open the door that is supposed to lead to the other rooms of the tardis, instead of seeing emptiness I'd see that the tardis interior has spawned underground an advanced rocketry planet. I really can't explain it better, I've been trying to reproduce but it's hard. Oh and on a side note, is the void supposed to be a low gravity environment? I can jump to the ceiling and land on the floor really slowly.

**Comment by Spectre0987** [comment]
No it's not. Advanced Rocketry is incredibly game breaking in the way they do things, but without a screen shot or videos I can't help you becuase I have no idea what you're talking about.

**Comment by Suffril** [comment]
Issue has become stale
