### ISSUE TITLE
Crash while trying to enter the TARDIS because of OTG (Open Terrain Generator)

### ISSUE THREAD

**Issue by NiceBergovich** [Spectre0987/TardisMod#79]
Crash while trying to enter the TARDIS because of OTG (Open Terrain Generator)
---- Minecraft Crash Report ----

WARNING: coremods are present:
  OTGCorePlugin (OTG-Core.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 10/26/18 8:28 PM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at com.pg85.otg.forge.dimensions.WorldProviderOTG.func_186058_p(WorldProviderOTG.java:62)
	at net.tardis.mod.client.renderers.decorations.hellbent.RenderHellbentMonitor.drawInfo(RenderHellbentMonitor.java:63)
	at net.tardis.mod.client.renderers.decorations.hellbent.RenderHellbentMonitor.func_192841_a(RenderHellbentMonitor.java:53)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:155)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:130)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:705)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.pg85.otg.forge.dimensions.WorldProviderOTG.func_186058_p(WorldProviderOTG.java:62)
	at net.tardis.mod.client.renderers.decorations.hellbent.RenderHellbentMonitor.drawInfo(RenderHellbentMonitor.java:63)
	at net.tardis.mod.client.renderers.decorations.hellbent.RenderHellbentMonitor.func_192841_a(RenderHellbentMonitor.java:53)

-- Block Entity Details --
Details:
	Name: tardis:tileentityhellbentmonitor // net.tardis.mod.common.tileentity.decoration.TileEntityHellbentMonitor
	Block type: ID #309 (tile.tardis.hellbent_monitor // net.tardis.mod.common.blocks.BlockMonitor // tardis:hellbent_monitor)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (269,9,264), Chunk: (at 13,0,8 in 16,16; contains blocks 256,0,256 to 271,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #309 (tile.tardis.hellbent_monitor // net.tardis.mod.common.blocks.BlockMonitor // tardis:hellbent_monitor)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:155)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:130)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:705)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Mr_Kek'/404, l='MpServer', x=257.50, y=6.00, z=262.50]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 06 - OTG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-709,53,-487), Chunk: (at 11,3,9 in -45,-31; contains blocks -720,0,-496 to -705,255,-481), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 70172 game time, 70509 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 24 total; [ControlLaunch['Time Rotor Handbrake'/384, l='MpServer', x=264.19, y=6.84, z=265.28], ControlX['Space Control - X'/385, l='MpServer', x=264.56, y=6.84, z=263.66], ControlY['Space Control - Y'/386, l='MpServer', x=264.47, y=6.84, z=263.66], ControlZ['Space Control - Z'/387, l='MpServer', x=264.38, y=6.84, z=263.66], ControlDimChange['Dimensional Control'/388, l='MpServer', x=264.63, y=6.84, z=265.34], ControlRandom['Control Randomizer'/389, l='MpServer', x=263.88, y=6.91, z=264.41], ControlSTCLoad['Waypoint Setter'/390, l='MpServer', x=263.91, y=6.84, z=265.06], ControlFlight['Real - World Flight Interface'/391, l='MpServer', x=265.13, y=6.88, z=264.88], ControlFuel['Refueler'/392, l='MpServer', x=265.34, y=6.81, z=264.38], ControlLandType['Landing Type Selector'/393, l='MpServer', x=265.34, y=6.84, z=264.75], ControlDirection['Directional Control'/394, l='MpServer', x=264.69, y=6.84, z=263.69], EntityHellbentDoor['entity.hellbent_door.name'/362, l='MpServer', x=258.00, y=6.00, z=262.00], ControlFastReturn['Fast Return'/395, l='MpServer', x=265.13, y=6.84, z=265.09], ControlDoor['Door'/363, l='MpServer', x=256.50, y=6.00, z=262.00], ControlTelepathicCircuts['Telepathic Circuits'/396, l='MpServer', x=264.50, y=6.88, z=263.88], ControlDoorSwitch['Door Switch'/397, l='MpServer', x=263.66, y=6.81, z=264.22], ControlMag['Coordinate Magnitude Adjuster'/398, l='MpServer', x=264.30, y=6.84, z=263.66], ControlPhone['Communicator'/399, l='MpServer', x=264.50, y=6.88, z=265.00], ControlSonicSlot['entity.sonic_slot.name'/400, l='MpServer', x=265.20, y=6.91, z=264.89], ControlSTCButton['Waypoint Selector'/401, l='MpServer', x=263.72, y=6.88, z=264.75], ControlSTCButton['Waypoint Selector'/402, l='MpServer', x=263.75, y=6.88, z=264.81], ControlSTCButton['Waypoint Selector'/403, l='MpServer', x=263.78, y=6.88, z=264.88], EntityHellbentCorridor['entity.hellbent_corridor.name'/405, l='MpServer', x=263.00, y=6.00, z=272.50], EntityPlayerSP['Mr_Kek'/404, l='MpServer', x=257.50, y=6.00, z=262.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 335702816 bytes (320 MB) / 771751936 bytes (736 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2765 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version           | Source                               | Signature                                |
	|:--------- |:-------------------- |:----------------- |:------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2            | minecraft.jar                        | None                                     |
	| UCHIJAAAA | mcp                  | 9.42              | minecraft.jar                        | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99         | forge-1.12.2-14.23.4.2765.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.4.2765      | forge-1.12.2-14.23.4.2765.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | otgcore              | 1.12.2 - v7       | minecraft.jar                        | None                                     |
	| UCHIJAAAA | openterraingenerator | v6                | OpenTerrainGenerator-1.12.2 - v6.jar | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
	| UCHIJAAAA | biomebundle          | 5.1               | Biome_Bundle-1.12.2-v6.1.jar         | None                                     |
	| UCHIJAAAA | ctm                  | MC1.12.2-0.3.2.20 | CTM-MC1.12.2-0.3.2.20.jar            | None                                     |
	| UCHIJAAAA | journeymap           | 1.12.2-5.5.2      | journeymap-1.12.2-5.5.2.jar          | None                                     |
	| UCHIJAAAA | tardis               | 0.0.7A            | tardis-0.0.7A.jar                    | None                                     |

	Loaded coremods (and transformers): 
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2765

**Comment by NiceBergovich** [comment]
Help Fix plz(

**Comment by LotuxPunk** [comment]
`at com.pg85.otg.forge.dimensions.WorldProviderOTG.func_186058_p(WorldProviderOTG.java:62)`

Maybe a bug with OTG ?

**Comment by SandedShoes** [comment]
Nah, it's on us. ``RenderHellbentMonitor`` is wanting to rendering information but the information is null, probably a stray null check in that class.
I'll take a look later tonight

**Comment by Suffril** [comment]
Fixed

**Comment by remo10000** [comment]
ich habe das selbe problem was kann ich da machen

---- Minecraft Crash Report ----

WARNING: coremods are present:
  OTGCorePlugin (OTG-Core.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 3/20/19 3:22 PM
Description: Exception in server tick loop

Missing Mods:
	unknown : need [14.23.5.2781,99999.24.0.0): have 14.23.5.2768

net.minecraftforge.fml.common.MissingModsException: Mod ichunutil (iChunUtil) requires [forge@[14.23.5.2781,99999.24.0.0)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.18-9-pve
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 710065808 bytes (677 MB) / 1150287872 bytes (1097 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 3 total; -Xmx6144M -Xms512M -XX:MaxPermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                          | Signature                                |
	|:----- |:-------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| U     | minecraft            | 1.12.2                   | minecraft.jar                                   | None                                     |
	| U     | mcp                  | 9.42                     | minecraft.jar                                   | None                                     |
	| U     | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2768-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | forge                | 14.23.5.2768             | forge-1.12.2-14.23.5.2768-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | otgcore              | 1.12.2 - v7              | minecraft.jar                                   | None                                     |
	| U     | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| U     | betteranimalsplus    | 5.0.1                    | betteranimalsplus-5.0.1.jar                     | None                                     |
	| U     | betterbuilderswands  | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| U     | biomebundle          | 5.1                      | Biome_Bundle-1.12.2-v6.1.jar                    | None                                     |
	| U     | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| U     | chisel               | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                    | None                                     |
	| U     | chiselsandbits       | 14.31                    | chiselsandbits-14.31.jar                        | None                                     |
	| U     | codechickenlib       | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | None                                     |
	| U     | crafttweaker         | 4.1.16                   | CraftTweaker2-1.12-4.1.16.jar                   | None                                     |
	| U     | crafttweakerjei      | 2.0.2                    | CraftTweaker2-1.12-4.1.16.jar                   | None                                     |
	| U     | cucumber             | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                       | None                                     |
	| U     | cyclicmagic          | 1.18.4                   | Cyclic-1.12.2-1.18.4.jar                        | None                                     |
	| U     | enderstorage         | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar     | None                                     |
	| U     | extrautils2          | 1.0                      | extrautils2-1.12-1.9.9.jar                      | None                                     |
	| U     | ichunutil            | 7.2.1                    | iChunUtil-1.12.2-7.2.1.jar                      | None                                     |
	| U     | jei                  | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                       | None                                     |
	| U     | journeymap           | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                     | None                                     |
	| U     | lootbags             | 2.5.8.5                  | LootBags-1.12.2-2.5.8.5.jar                     | None                                     |
	| U     | mantle               | 1.12-1.3.3.42            | Mantle-1.12-1.3.3.42.jar                        | None                                     |
	| U     | mcjtylib_ng          | 3.1.1                    | mcjtylib-1.12-3.1.1.jar                         | None                                     |
	| U     | megaloot             | 0.2.30                   | megaloot-1.12.2-0.2.30.jar                      | None                                     |
	| U     | mysticalagriculture  | 1.7.3                    | MysticalAgriculture-1.12.2-1.7.3.jar            | None                                     |
	| U     | openterraingenerator | v6                       | OpenTerrainGenerator-1.12.2 - v6.jar            | None                                     |
	| U     | oreberries           | 0.5.0                    | oreberries-1.12.x-0.5.0.jar                     | None                                     |
	| U     | oreexcavation        | 1.4.137                  | OreExcavation-1.4.137.jar                       | None                                     |
	| U     | harvestcraft         | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zb.jar                 | None                                     |
	| U     | pamscookables        | 1.1                      | pamscookables-1.1.jar                           | None                                     |
	| U     | refinedstorage       | 1.6.12                   | refinedstorage-1.6.12.jar                       | None                                     |
	| U     | rftools              | 7.61                     | rftools-1.12-7.61.jar                           | None                                     |
	| U     | solarflux            | 4.32r                    | SolarFluxReborn_1.12.2-4.32r.jar                | None                                     |
	| U     | solarfurnace         | 1.0                      | SolarfurnaceMC1.12.2-1.1.jar                    | None                                     |
	| U     | soulshardsrespawn    | 1.12.2-1.1.0-12          | SoulShardsRespawn-1.12.2-1.1.0-12.jar           | None                                     |
	| U     | storagedrawers       | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                 | None                                     |
	| U     | tconstruct           | 1.12.2-2.12.0.115        | TConstruct-1.12.2-2.12.0.115.jar                | None                                     |
	| U     | tinkertoolleveling   | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar             | None                                     |
	| U     | tp                   | 3.2.32                   | tinyprogressions-1.12.2-3.3.32-Release.jar      | None                                     |
	| U     | waystones            | 4.0.67                   | Waystones_1.12.2-4.0.67.jar                     | None                                     |
	| U     | matteroverdrive      | 0.7.0.16                 | MatterOverdrive-1.12.2-0.7.0.16-universal.jar   | None                                     |

	Loaded coremods (and transformers): 
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by remo10000** [comment]
Was kann ich machen das dises problem nicht mehr kommt

---- Minecraft Crash Report ----

WARNING: coremods are present:
  OTGCorePlugin (OTG-Core.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 3/20/19 3:22 PM
Description: Exception in server tick loop

Missing Mods:
	unknown : need [14.23.5.2781,99999.24.0.0): have 14.23.5.2768

net.minecraftforge.fml.common.MissingModsException: Mod ichunutil (iChunUtil) requires [forge@[14.23.5.2781,99999.24.0.0)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.18-9-pve
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 710065808 bytes (677 MB) / 1150287872 bytes (1097 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 3 total; -Xmx6144M -Xms512M -XX:MaxPermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                          | Signature                                |
	|:----- |:-------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| U     | minecraft            | 1.12.2                   | minecraft.jar                                   | None                                     |
	| U     | mcp                  | 9.42                     | minecraft.jar                                   | None                                     |
	| U     | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2768-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | forge                | 14.23.5.2768             | forge-1.12.2-14.23.5.2768-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| U     | otgcore              | 1.12.2 - v7              | minecraft.jar                                   | None                                     |
	| U     | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| U     | betteranimalsplus    | 5.0.1                    | betteranimalsplus-5.0.1.jar                     | None                                     |
	| U     | betterbuilderswands  | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| U     | biomebundle          | 5.1                      | Biome_Bundle-1.12.2-v6.1.jar                    | None                                     |
	| U     | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| U     | chisel               | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                    | None                                     |
	| U     | chiselsandbits       | 14.31                    | chiselsandbits-14.31.jar                        | None                                     |
	| U     | codechickenlib       | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | None                                     |
	| U     | crafttweaker         | 4.1.16                   | CraftTweaker2-1.12-4.1.16.jar                   | None                                     |
	| U     | crafttweakerjei      | 2.0.2                    | CraftTweaker2-1.12-4.1.16.jar                   | None                                     |
	| U     | cucumber             | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                       | None                                     |
	| U     | cyclicmagic          | 1.18.4                   | Cyclic-1.12.2-1.18.4.jar                        | None                                     |
	| U     | enderstorage         | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar     | None                                     |
	| U     | extrautils2          | 1.0                      | extrautils2-1.12-1.9.9.jar                      | None                                     |
	| U     | ichunutil            | 7.2.1                    | iChunUtil-1.12.2-7.2.1.jar                      | None                                     |
	| U     | jei                  | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                       | None                                     |
	| U     | journeymap           | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                     | None                                     |
	| U     | lootbags             | 2.5.8.5                  | LootBags-1.12.2-2.5.8.5.jar                     | None                                     |
	| U     | mantle               | 1.12-1.3.3.42            | Mantle-1.12-1.3.3.42.jar                        | None                                     |
	| U     | mcjtylib_ng          | 3.1.1                    | mcjtylib-1.12-3.1.1.jar                         | None                                     |
	| U     | megaloot             | 0.2.30                   | megaloot-1.12.2-0.2.30.jar                      | None                                     |
	| U     | mysticalagriculture  | 1.7.3                    | MysticalAgriculture-1.12.2-1.7.3.jar            | None                                     |
	| U     | openterraingenerator | v6                       | OpenTerrainGenerator-1.12.2 - v6.jar            | None                                     |
	| U     | oreberries           | 0.5.0                    | oreberries-1.12.x-0.5.0.jar                     | None                                     |
	| U     | oreexcavation        | 1.4.137                  | OreExcavation-1.4.137.jar                       | None                                     |
	| U     | harvestcraft         | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zb.jar                 | None                                     |
	| U     | pamscookables        | 1.1                      | pamscookables-1.1.jar                           | None                                     |
	| U     | refinedstorage       | 1.6.12                   | refinedstorage-1.6.12.jar                       | None                                     |
	| U     | rftools              | 7.61                     | rftools-1.12-7.61.jar                           | None                                     |
	| U     | solarflux            | 4.32r                    | SolarFluxReborn_1.12.2-4.32r.jar                | None                                     |
	| U     | solarfurnace         | 1.0                      | SolarfurnaceMC1.12.2-1.1.jar                    | None                                     |
	| U     | soulshardsrespawn    | 1.12.2-1.1.0-12          | SoulShardsRespawn-1.12.2-1.1.0-12.jar           | None                                     |
	| U     | storagedrawers       | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                 | None                                     |
	| U     | tconstruct           | 1.12.2-2.12.0.115        | TConstruct-1.12.2-2.12.0.115.jar                | None                                     |
	| U     | tinkertoolleveling   | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar             | None                                     |
	| U     | tp                   | 3.2.32                   | tinyprogressions-1.12.2-3.3.32-Release.jar      | None                                     |
	| U     | waystones            | 4.0.67                   | Waystones_1.12.2-4.0.67.jar                     | None                                     |
	| U     | matteroverdrive      | 0.7.0.16                 | MatterOverdrive-1.12.2-0.7.0.16-universal.jar   | None                                     |

	Loaded coremods (and transformers): 
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by CommandrMoose** [comment]
If you have an issue, please create a separate thread from others in the future.

`net.minecraftforge.fml.common.MissingModsException: Mod ichunutil (iChunUtil) requires [forge@[14.23.5.2781,99999.24.0.0)]`

This has nothing to do with us. Please update your other mods.

**Comment by LotuxPunk** [comment]
Du hast die Version von Forge ist falsch.

**Comment by remo10000** [comment]
wen ich mal fragen darf welche forge wäre dan die richtige ?

**Comment by AwesomeAnimationGamer** [comment]
Unfortunately this is still happening for me, here's my crash log:
[crash-2019-04-03_19.14.33-client.txt](https://github.com/Spectre0987/TardisMod/files/3041084/crash-2019-04-03_19.14.33-client.txt)
