### ISSUE TITLE
The game (client) does not start - "Failed to register dimension for id 2"

### ISSUE THREAD

**Issue by DoctorGray** [Spectre0987/TardisMod#80]
Hey guys,

my brother is an admin of his own server.
We use the Feed The Beast Launcher and the Direwolf20 1.12 (v2.3.0) Modpack. We added a few mods like decocraft, furniture mod, malisis doors and a tail mod.

So when we try to launch the game (or even the server) it tries to load the game and crashes before we could see the main menu.

Crash Report:
https://pastebin.com/YCwvmDaF

Yesterday we deleted a few mods from the server because of some performance issues, but it makes no difference.

Deleted Mods:
binnie mods
DankNull
gendustry
morph
morph-o-tool
NetherPortalFix
pneumaticcraft
xnet

I hope you guys have a solution. I really loved the old tardis-mod and would like to see the new one.

**Comment by honeyluck** [comment]
If you navigate to the TARDIS Mod config file you can change the dimension IDs for our mod to make sure that they do not conflict
