### ISSUE TITLE
Crash when loading the server

### ISSUE THREAD

**Issue by Gamerbolts** [Spectre0987/TardisMod#87]
Hi, I am creating a modpack and was testing things, the client loaded fine, but the server crashed while creating the world. Here is the crash log https://pastebin.com/ghMt2aQ8

Any help is appreciated. Thank you!

**Comment by Suffril** [comment]
Just fixed this in the latest commit, I'll release it later..maybe, just depends

**Comment by Gamerbolts** [comment]
awesome! Ty will patiently wait.

**Comment by Spectre0987** [comment]
Yeah, I'll release a general bug fix soon, and Sub's already fixed this issue, so it should be included.
