### ISSUE TITLE
Entities that enter TARDIS do not appear in TARDIS

### ISSUE THREAD

**Issue by chaNcharge** [Spectre0987/TardisMod#88]
In 0.0.8 on a singleplayer world, any entities besides the player that enter the TARDIS do not appear in the TARDIS. A warning is produced in the log:
`[Server thread/WARN] [net.minecraft.world.WorldServer]: Keeping entity minecraft:cow that already exists with UUID ...`

To reproduce:
1. Get a TARDIS and open the doors, but do not go inside yet
2. Spawn any entity and make it go in the TARDIS
3. Observe by going in the TARDIS after the entity entered it

**Comment by 50ap5ud5** [comment]
The same behaviour can be seen in multiplayer, most notably in the Official Tardis Mod server which is running 0.0.8A Hotfix 2

**Comment by Spectre0987** [comment]
Never looked into it past that because this is news to me.

**Comment by Spectre0987** [comment]
Or it might have been me actually...

**Comment by Suffril** [comment]
Closed in https://github.com/Spectre0987/TardisMod/commit/0a3d984f12fd95d68cb827eba78b8736bd13e038
