### ISSUE TITLE
Client is crashing when AE2 and This mod are loading together

### ISSUE THREAD

**Issue by supersquids12** [Spectre0987/TardisMod#89]
I was playing on a modpack that my friend makes and he has a server to accompany it. We wanted to add the TARDIS Mod but it seemed as if it crashed whenever we tried to load it. Looking through the logs I can see an error with AE2(Applied Energistics 2) whenever the two mods are coexisting. I tested through this a bit and all results seem to point to that conclusion. Could you help with this? I would really like to be able to use this mod in the pack. Thanks for taking the time to read this!

**Comment by PurpleHel** [comment]
Also getting this. Crash is a dimension ID issue. Log https://pastebin.com/jNCeu5zU

@supersquids12  in the meantime, try tardis-0.0.7A, it's working for me.

**Comment by Suffril** [comment]
I mean you could do that lose out on all the new things.
Alternatively, edit the config to change the dimension ids and enable the change.

**Comment by PurpleHel** [comment]
'cept for my crash, it's saying ID 4, and none of the dimensions are set in the config file to ID 4, so I have no way of knowing which dimension ID to change.

**Comment by PurpleHel** [comment]
I:spaceDimension=66622
        I:tardisDimension=66610
        I:telosDimension=66623

Still crashes, same error.

**Comment by supersquids12** [comment]
I set mine to 1991, 1992, and 1993, and it still crashed :(

**Comment by Suffril** [comment]
You must enable the option in the config to use these new numbers

**Comment by supersquids12** [comment]
I'm a little new to messing with configs, how does one go about that?(Sorry, I'm just bad at this stuff xD)

**Comment by supersquids12** [comment]
I just tried these settings:
B:USE_WHITELIST=true
B:setDimension=true
_________________________
B:USE_WHITELIST=false
B:setDimension=true
________________________
B:USE_WHITELIST=true
B:setDimension=false

None of them worked x3

**Comment by Suffril** [comment]
```# Configuration file

general {
    B:boti=true

    dimensions {
        B:USE_WHITELIST=false
        I:bDims <
            1
         >
        B:setDimension=true
        I:spaceDimension=22
        I:tardisDimension=10
        I:telosDimension=23
    }

    use_entities {
        I:adiposeSpawnChance=10
        I:cybermanSpawnChance=50
        B:entities=true
    }

    misc {
        B:camShake=true
        B:givePlayerKey=false
        B:invasions=true
        B:killControlsOnKillCommand=false

        # Set to Zero to make it anywhere in the world.
        I:maxRandom=5000
    }

    boti {
        B:enabled=true
        S:modids <
         >
    }

}
```

![2018-11-11_12 32 30](https://user-images.githubusercontent.com/36424503/48312950-ec380f80-e5ad-11e8-99ed-32d11d9b58d2.png)


Works fine for me. Perhaps don't make your choosen IDs for the dimensions so high.

**Comment by PurpleHel** [comment]
Minecraft supports "high" dimension IDs. I've got dimensions with IDs - 11325,-343800852, - 9999, and 1486248640. They all work fine. Which version of AE2 are you testing with, Suffril?

**Comment by PurpleHel** [comment]
Hmm. Copied in your config wholesale and it works. @supersquids12, give it a try?

**Comment by supersquids12** [comment]
[B#397]  // This doesn't make any sense!
[B#397]  
[B#397]  Time: 11/11/18 12:32 PM
[B#397]  Description: There was a severe problem during mod loading that has caused the game to fail
[B#397]  
[B#397]  net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 2 (appliedenergistics2)
[B#397]  Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 2, One is already registered
[B#397]  	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:134)
[B#397]  	at appeng.core.Registration.registerSpatialDimension(Registration.java:201)
[B#397]  	at appeng.core.Registration.postInit(Registration.java:352)
[B#397]  	at appeng.core.AppEng.postInit(AppEng.java:233)
[B#397]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#397]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#397]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#397]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#397]  	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
[B#397]  	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
[B#397]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#397]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#397]  	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[B#397]  	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[B#397]  	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[B#397]  	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[B#397]  	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[B#397]  	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[B#397]  	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[B#397]  	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
[B#397]  	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
[B#397]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#397]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#397]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#397]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#397]  	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[B#397]  	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[B#397]  	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[B#397]  	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[B#397]  	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[B#397]  	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[B#397]  	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[B#397]  	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
[B#397]  	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
[B#397]  	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
[B#397]  	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
[B#397]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
[B#397]  	at net.minecraft.client.main.Main.main(SourceFile:123)
[B#397]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#397]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#397]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#397]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#397]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#397]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


Same error

**Comment by supersquids12** [comment]
Anyone got any other ideas? xD Or if I just didn't do something right please tell me

**Comment by Spectre0987** [comment]
Upload your Config file and tell me where in your .minecraft folder it is.

**Comment by supersquids12** [comment]
[TARDIS Mod.zip](https://github.com/Spectre0987/TardisMod/files/2582821/TARDIS.Mod.zip)
For this I'm using a modpack my friend created, but I'm allowed to suggest things.
C:\Users\Robert\AppData\Roaming\.technic\modpacks\galactic-magitech

**Comment by Spectre0987** [comment]
I'm gonna assume it's not in a zip file?

**Comment by supersquids12** [comment]
Nope

**Comment by enderger** [comment]
This issue affects me. AE2's spacial storage dimension is the issue: one of the dimesions in this mod is registering as ID 2

**Comment by Suffril** [comment]
Next Patch will fix it, don't worry, it's either coming today or tomorrow

**Comment by enderger** [comment]
Ok. It should just be a case of switching whichever dimension id 2 is to a different number.

**Comment by Suffril** [comment]
Well it is, but that seems to confuse some people

**Comment by enderger** [comment]
What dimension has an id of 2 by default(I want to make the current patch work)

**Comment by Suffril** [comment]
None of them have two by default, the mod finds a specific free dimension when we register our dimensions
Looks like @Spectre0987 messed up when adding the moon dimension though, he didn't add it to the config

**Comment by enderger** [comment]
I'll try to change AE's dimension.

**Comment by enderger** [comment]
I have a temporary fix:

change the following line in AE's config to not have a value of 2.
`I:storageDimensionID=2`

**Comment by enderger** [comment]
Also, while on the subject of updates, can a JEI plugin be added for this mod?

**Comment by Suffril** [comment]
https://github.com/Spectre0987/TardisMod/tree/master/src/main/java/net/tardis/mod/integrations

It's a work in progress on Spectres side

**Comment by enderger** [comment]
Also, if you materialise around a player and he’s pushed out still, a non-solid portal block could be used for the animation and switches to the tardis block when fully materialised

**Comment by Suffril** [comment]
Please join the discord to give suggestions, the issue tracker isn't the place
