### ISSUE TITLE
Dedicated server crash when trying to enter TARDIS

### ISSUE THREAD

**Issue by UniversalMigrator** [Spectre0987/TardisMod#9]
Trying to enter TARDIS on dedicated server, doors unlock and open fine, trying to enter results in server crash, with relog attempts resulting in the same server crash.

Using Forge 2707.

https://pastebin.com/Af2tUhp0

**Comment by LotuxPunk** [comment]
Same bug apparently, but my server won't crash juste timed out me again & again https://pastebin.com/m5cpDRPh
