### ISSUE TITLE
Multiple crashes on server because of unknown reasons

### ISSUE THREAD

**Issue by Mrleplayz** [Spectre0987/TardisMod#90]
So me and my brother have this survival world where we built some quite awesome stuff and we'd hate to lose all of it. We decided to use the new Tardis mod in our world because we're both fond of the show and could utilise it in a lot of situations.

We used only ONE Tardis, it grew and was ready to be used. Then the 0.0.8 update came out and I thought stuff was gonna break. So I recharged the Artron energy, installed the dematerialisation circuit etc...

The Tardis worked, but then, all of a sudden, when I opened the door of the Tardis my game crashed.

I loaded up the world again and it crashed immediately upon server load.

I deleted all files related to the mod inside the world folder to completely remove it from the world.
The Tardis had disappeared. I grew another one and it crashed again when opening the door.

I once again deleted the Tardis dimension and files from the world folder. This time i removed optifine.
I grew a 3rd Tardis and it worked! BUT then once i looked at the door, all entities inside the Tardis became black and unusable, like i couldn't interact with the console, the monitor, the door just straight up disappeared.

This IS a lot of text but I feel like the context was really important here.

I would suggest making the BOTI update optional in the Monitor menu inside the Tardis, it could prevent stuff like this completely.

Here's the crash log I got when looking through the door : 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.5-130.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 11/10/18 11:56 AM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at net.tardis.mod.client.worldshell.WorldShell.func_175625_s(WorldShell.java:60)
	at net.tardis.mod.client.worldshell.WorldBoti.func_175625_s(WorldBoti.java:38)
	at net.tardis.mod.client.renderers.controls.RenderDoor.doRender(RenderDoor.java:47)
	at net.tardis.mod.client.renderers.controls.RenderDoor.func_76986_a(RenderDoor.java:23)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:416)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:393)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:827)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1800)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1384)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.tardis.mod.client.worldshell.WorldShell.func_175625_s(WorldShell.java:60)
	at net.tardis.mod.client.worldshell.WorldBoti.func_175625_s(WorldBoti.java:38)
	at net.tardis.mod.client.renderers.controls.RenderDoor.doRender(RenderDoor.java:47)
	at net.tardis.mod.client.renderers.controls.RenderDoor.func_76986_a(RenderDoor.java:23)

-- Entity being rendered --
Details:
	Entity Type: tardis:tardis_door (net.tardis.mod.common.entities.controls.ControlDoor)
	Entity ID: 1074
	Entity Name: Door
	Entity's Exact location: 256.50, 6.00, 262.00
	Entity's Block location: World: (256,6,262), Chunk: (at 0,0,6 in 16,16; contains blocks 256,0,256 to 271,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.tardis.mod.client.renderers.controls.RenderDoor@aea6107
	Location: -2.50,0.00,-0.00 - World: (-3,0,-1), Chunk: (at 13,0,15 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: -90.0
	Delta: 0.3600006
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:416)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:393)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:827)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1800)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1613)

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3 game time, 204167 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 381391096 bytes (363 MB) / 1031020544 bytes (983 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 7, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E2 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State          | ID                   | Version      | Source                                                       | Signature                                |
	|:-------------- |:-------------------- |:------------ |:------------------------------------------------------------ |:---------------------------------------- |
	| UCHIJAAAAAAAAA | minecraft            | 1.12.2       | minecraft.jar                                                | None                                     |
	| UCHIJAAAAAAAAA | mcp                  | 9.42         | minecraft.jar                                                | None                                     |
	| UCHIJAAAAAAAAA | FML                  | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAA | forge                | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAA | movillages           | 1.5.4        | [1.12]MoVillages-1.5.4.jar                                   | None                                     |
	| UCHIJAAAAAAAAA | additionalstructures | 1.6.0        | Additional+Structures+1.12.2+by+XxRexRaptorxX++(v.1.6.0).jar | None                                     |
	| UCHIJAAAAAAAAA | quark                | r1.5-130     | Quark-r1.5-130.jar                                           | None                                     |
	| UCHIJAAAAAAAAA | autoreglib           | 1.3-20       | AutoRegLib-1.3-20.jar                                        | None                                     |
	| UCHIJAAAAAAAAA | customnpcs           | 1.12         | CustomNPCs_1.12.2(20jan18).jar                               | None                                     |
	| UCHIJAAAAAAAAA | fastleafdecay        | v14          | FastLeafDecay-v14.jar                                        | None                                     |
	| UCHIJAAAAAAAAA | jei                  | 4.9.1.187    | jei_1.12.2-4.9.1.187.jar                                     | None                                     |
	| UCHIJAAAAAAAAA | journeymap           | 1.12.2-5.5.2 | journeymap-1.12.2-5.5.2.jar                                  | None                                     |
	| UCHIJAAAAAAAAA | oreexcavation        | 1.4.129      | OreExcavation-1.4.129.jar                                    | None                                     |
	| UCHIJAAAAAAAAA | tardis               | 0.0.8A       | tardis-0.0.8A.jar                                            | None                                     |
	| UCHIJAAAAAAAAA | worldedit            | 6.1.8        | worldedit-forge-mc1.12-6.1.8-dist.jar                        | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.5-130.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13521 Compatibility Profile Context 24.20.11016.4' Renderer: 'AMD Radeon (TM) R7 360 Series'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: AMD Radeon (TM) R7 360 Series GL version 4.5.13521 Compatibility Profile Context 24.20.11016.4, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD Athlon(tm) X4 845 Quad Core Processor

**Comment by LotuxPunk** [comment]
Disable the BOTI in the config file

**Comment by Spectre0987** [comment]
Check the mod's config for the BOTI option. That being said, that crash should be fixed with Hotfix one.
