### ISSUE TITLE
Setting givePlayerKey=true behaviour

### ISSUE THREAD

**Issue by EvertX** [Spectre0987/TardisMod#91]
When I set givePlayerKey=true in the config, it doesn't give me a key but coral and it does so every time I enter the world (not just the first time).

**Comment by EvertX** [comment]
Very well, but that doesn't explain why I get one every login :)

**Comment by LotuxPunk** [comment]
I didn't understand that: D

**Comment by EvertX** [comment]
It stops once a tardis has grown.

**Comment by Spectre0987** [comment]
This is mostly intentional in case something happens to it.
