### ISSUE TITLE
Crash after a lot of lag

### ISSUE THREAD

**Issue by LotuxPunk** [Spectre0987/TardisMod#92]
https://pastebin.com/wVeLbArG

**Comment by Suffril** [comment]
Seems to be having issues based on lua based thread, are you sure this is on us?

**Comment by LotuxPunk** [comment]
People tended to say it came from the communicator, and I have no function for communications

**Comment by Spectre0987** [comment]
Seems to be that  ws.getChunkProvider().getNearestStructurePos(ws, "Village", tardis.getLocation(), true); is the cause, not sure how to stop the lag as there's no argument for a range...

**Comment by LotuxPunk** [comment]
https://pastebin.com/3dRLvhbP

Another crash report
