### ISSUE TITLE
CCL freaks out in tardis

### ISSUE THREAD

**Issue by enderger** [Spectre0987/TardisMod#98]
CCL Caught an exception rendering a block. See log for details.

Spams my chat in the TARDIS

**Comment by Suffril** [comment]
It would be lovely if you could tell us what ccl even is, but before you do that, try adding that mods mod id to the part of the config where it asks for mod ids

**Comment by enderger** [comment]
I think that this doesn’t just affect CCL: it seems to be linked to the disappearance of items from the player’s hand

**Comment by enderger** [comment]
CCL is apparently Code Chicken Lib, this is bigger than I thought.

**Comment by enderger** [comment]
I think that this is a BOTI bug

**Comment by Suffril** [comment]
It's known

**Comment by enderger** [comment]
It also extends to the tardis itself

**Comment by Spectre0987** [comment]
Do you wanna post the log file? "Freaks out" isn't the most technical explanation I've heard.

**Comment by enderger** [comment]
[13:58:05] [main/INFO] [STDERR]: [net.tardis.mod.util.client.RenderHelper:setRenderGlobalWorld:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

Repeats whenever the glitch occurs

**Comment by Spectre0987** [comment]
Are you using Optifine?

**Comment by enderger** [comment]
No, that would be foolish on the modpack I am playing.

**Comment by Spectre0987** [comment]
Can I have the full log please?

**Comment by enderger** [comment]
Ok

https://gist.githubusercontent.com/enderger/1de5b143923d5697553140599e25063e/raw/91399393431cf78563914ca6bdce91d9fb8ab692/renderhelper.log

**Comment by Suffril** [comment]
What name do you need?

**Comment by Spectre0987** [comment]
Only ting I can thing is that CCL has to have changed the variable name.
